// This file is generated by bedrock. Do not edit by hand.
declare const resources: {
	readonly development: {};
	readonly production: {
		readonly "gem-pack": {
			readonly iconImageAssetId: number;
			readonly productId: number;
		};
		readonly main: {
			readonly rootPlaceId: number;
		};
		readonly "start-place": {
			readonly versionNumber: number;
		};
		readonly "vip-pass": {
			readonly assetId: number;
			readonly iconAssetIds: {
				readonly "en-us": number;
			};
		};
	};
	readonly staging: {
		readonly "gem-pack": {
			readonly productId: number;
		};
		readonly "vip-pass": {
			readonly assetId: number;
			readonly iconAssetIds: {
				readonly "en-us": number;
			};
		};
	};
};
export = resources;
