import { stringifyYAML } from "confbox";

import type { Config } from "../schema.ts";

/**
 * Inputs for {@link serializeConfig}. The migrator stamps each emitted
 * config file with a header that lets a future reader audit which
 * migrator run produced it, which Mantle state file it was derived from,
 * and when that happened. Format dispatch lives on `configFormat` so a
 * single function shape covers both TypeScript and YAML output.
 */
export interface SerializeConfigOptions {
	/** Validated bedrock config to render. */
	readonly config: Config;
	/** Output format. TypeScript emits `defineConfig({...})`; YAML emits a `bedrock.config.yaml` body. */
	readonly configFormat: "typescript" | "yaml";
	/** Wall-clock time the migration ran. Stamped into the generated-file header. */
	readonly generatedAt: Date;
	/** Bedrock migrator version. Stamped into the generated-file header. */
	readonly migratorVersion: string;
	/** Path of the source `.mantle-state.yml` file. Stamped into the generated-file header. */
	readonly sourceStatePath: string;
}

/**
 * Render a bedrock `Config` as the source text of a `bedrock.config.{ts,yaml}`
 * file the user can write straight to disk. Both branches prefix the
 * payload with a two-line `Generated by` comment block (TypeScript-style
 * `//` or YAML-style `#`) carrying the migrator version, the source state
 * path, and the migration timestamp so a future reader can audit
 * provenance.
 *
 * The TypeScript branch hand-rolls a `JSON.stringify`-based emitter (no
 * AST library): the formatter quotes every property name, which is valid
 * TypeScript and sidesteps the need for an identifier-vs-quoted
 * heuristic. The YAML branch delegates to `stringifyYAML`, which already
 * drops `undefined`-valued properties so the output never surfaces
 * `null` or `~` for absent managed fields. Both shapes round-trip
 * through `loadConfig` cleanly.
 *
 * @param options - Render inputs.
 * @returns A UTF-8 source string ending with a trailing newline.
 */
export function serializeConfig(options: SerializeConfigOptions): string {
	const header = renderHeader(options);
	if (options.configFormat === "yaml") {
		return `${header}\n\n${stringifyYAML(options.config)}\n`;
	}

	const body = JSON.stringify(options.config, undefined, 2);
	return [
		header,
		"",
		'import { defineConfig } from "@bedrock/core";',
		"",
		`export default defineConfig(${body});`,
		"",
	].join("\n");
}

function renderHeader(options: SerializeConfigOptions): string {
	const prefix = options.configFormat === "yaml" ? "#" : "//";
	const timestamp = options.generatedAt.toISOString();
	return [
		`${prefix} Generated by bedrock migrate v${options.migratorVersion} from ${options.sourceStatePath} at ${timestamp}`,
		`${prefix} Do not edit by hand.`,
	].join("\n");
}
