// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { classifyS3Failure } from '@bedrock-rbx/state-s3'

it('Example 1', () => {
  const refusal = Object.assign(new Error('Access Denied'), {
    $metadata: { httpStatusCode: 403 },
    name: 'AccessDenied',
  })
  expect(classifyS3Failure(refusal).kind).toBe('accessDenied')
})
