// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { HttpRequest } from '@smithy/core/protocols'
import { createFetchRequestHandler } from '@bedrock-rbx/state-s3'

it('Example 1', () => {
  const handler = createFetchRequestHandler(
    async () => new Response('', { status: 200 }),
  )
  return handler
    .handle(
      new HttpRequest({
        headers: {},
        hostname: 'my-bucket.s3.eu-west-2.amazonaws.com',
        method: 'GET',
        path: '/production.json',
        protocol: 'https:',
      }),
    )
    .then(({ response }) => {
      expect(response.statusCode).toBe(200)
    })
})
