// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { objectKeyFor, objectLabelFor } from '@bedrock-rbx/state-s3'

it('Example 1', () => {
  expect(objectKeyFor('bedrock/state', 'production')).toBe(
    'bedrock/state/production.json',
  )
  expect(objectKeyFor(undefined, 'production')).toBe('production.json')
})

it('Example 2', () => {
  expect(objectLabelFor('my-bucket', 'production.json')).toBe(
    's3://my-bucket/production.json',
  )
})
