// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import s3Plugin, { s3StateBackend } from '@bedrock-rbx/state-s3'

it('Example 1', () => {
  const built = s3StateBackend.createPort({
    fetch: async () => new Response('', { status: 200 }),
    getEnv: () => undefined,
    stateConfig: { bucket: 'my-bucket', region: 'eu-west-2' },
  })
  expect(s3StateBackend.name).toBe('s3')
  expect(built.success).toBeTrue()
})

it('Example 2', () => {
  expect(s3Plugin.stateBackends).toHaveLength(1)
})
