// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { createS3StateAdapter } from '@bedrock-rbx/state-s3'

it('Example 1', () => {
  const port = createS3StateAdapter({
    bucket: 'my-bucket',
    credentials: {
      accessKeyId: 'example-access-key',
      secretAccessKey: 'example-secret',
    },
    fetch: async () =>
      new Response('<Error><Code>NoSuchKey</Code></Error>', { status: 404 }),
    region: 'eu-west-2',
  })
  return port.read('production').then((state) => {
    expect(state.success).toBeTrue()
    if (state.success) {
      expect(state.data.state).toBeUndefined()
    }
  })
})
