// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { createS3StateLockPort } from '@bedrock-rbx/state-s3'

it('Example 1', () => {
  const port = createS3StateLockPort({
    bucket: 'my-bucket',
    credentials: {
      accessKeyId: 'example-access-key',
      secretAccessKey: 'example-secret',
    },
    fetch: async () =>
      new Response('', { headers: { etag: '"held"' }, status: 200 }),
    owner: 'ci-run-7',
    region: 'eu-west-2',
  })
  return port
    .acquire('production', { operation: 'deploy' })
    .then(async (hold) => {
      expect(hold.success).toBeTrue()
      if (hold.success) {
        const given = await hold.data.release()
        expect(given.success).toBeTrue()
      }
    })
})
