// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { s3StateSchema } from '@bedrock-rbx/state-s3'

it('Example 1', () => {
  const parsed = s3StateSchema({ bucket: 'my-bucket', region: 'eu-west-2' })
  expect(parsed).toStrictEqual({ bucket: 'my-bucket', region: 'eu-west-2' })
})
