// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { DeveloperProductsClient } from '@bedrock-rbx/ocale/developer-products'

it('Example 1', () => {
  const client = new DeveloperProductsClient({ apiKey: 'your-key' })
  expect(client).toBeInstanceOf(DeveloperProductsClient)
})
