// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { GamePassesClient } from '@bedrock-rbx/ocale/game-passes'

it('Example 1', () => {
  const client = new GamePassesClient({ apiKey: 'your-key' })
  expect(client).toBeInstanceOf(GamePassesClient)
})
