[env]
_.path = [ '{{config_root}}/node_modules/.bin' ]
_.file = { path = ".env", redact = true }

[settings]
experimental = true

[tools]
bun = "1.3.4"
node = { version = "lts", postinstall = "corepack enable" }

