// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { RestartPlaceFilter } from '@bedrock-rbx/ocale/universes'

it('Example 1', () => {
  const places: Record<string, RestartPlaceFilter> = {
    111: {},
    222: { versions: [4, 5] },
    333: { excludeCurrentVersion: true },
  }
  expect(Object.keys(places)).toEqual(['111', '222', '333'])
})
