// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { UniversesClient } from '@bedrock-rbx/ocale/universes'

it('Example 1', () => {
  const client = new UniversesClient({ apiKey: 'your-key' })
  expect(client).toBeInstanceOf(UniversesClient)
})
