// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { createFakeHttpClient } from '@bedrock-rbx/ocale/testing'
import { UniversesClient } from '@bedrock-rbx/ocale/universes'

it('Example 1', () => {
  const httpClient = createFakeHttpClient().mockResponse({
    body: {
      id: '00000000-0000-0000-0000-000000000000',
      instancesImpacted: 0,
      playersImpacted: 0,
    },
    status: 200,
  })
  const client = new UniversesClient({ apiKey: 'your-key', httpClient })
  return client.restarts
    .launch({ bleedOffDurationMinutes: 5, universeId: '42' })
    .then((result) => {
      expect(result).toEqual({
        data: { id: undefined, instancesImpacted: 0, playersImpacted: 0 },
        success: true,
      })
    })
})
