// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { LuauExecutionCapacityError } from '@bedrock-rbx/ocale/luau-execution'

it('@since unreleased', () => {
  const error = new LuauExecutionCapacityError([
    {
      placeId: '456',
      sessionId: '11111111-1111-4111-8111-111111111111',
      taskId: '22222222-2222-4222-8222-222222222222',
      universeId: '123',
      versionId: '789',
    },
  ])
  expect(error.blockers).toHaveLength(1)
})
