// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { LuauExecutionClient } from '@bedrock-rbx/ocale/luau-execution'

it('Example 1', () => {
  const client = new LuauExecutionClient({ apiKey: 'your-key' })
  expect(client).toBeInstanceOf(LuauExecutionClient)
})
