// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { defaultPollDelay } from '@bedrock-rbx/ocale/luau-execution'

it('Example 1', () => {
  expect(defaultPollDelay(0)).toBe(500)
  expect(defaultPollDelay(30000)).toBe(1000)
  expect(defaultPollDelay(120000)).toBe(5000)
})
