// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  type ApplyError,
  type AggregateApplyError,
  applyOps,
  type DriverRegistry,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  function describe(err: ApplyError): string {
    switch (err.kind) {
      case 'driverFailure': {
        return `driver failed for ${err.key}: ${err.cause.message}`
      }
      case 'unexpectedThrow': {
        return `unexpected error for ${err.key}`
      }
      case 'updateUnsupported': {
        return `update not supported for ${err.key}`
      }
    }
  }
  const err: ApplyError = {
    key: asResourceKey('vip-pass'),
    kind: 'updateUnsupported',
  }
  expect(describe(err)).toBe('update not supported for vip-pass')
})

it('Example 2', () => {
  function summarize(err: AggregateApplyError): string {
    return `${err.applied.length} survived, ${err.failures.length} failed`
  }
  const err: AggregateApplyError = {
    applied: [],
    failures: [{ key: asResourceKey('vip-pass'), kind: 'updateUnsupported' }],
  }
  expect(summarize(err)).toBe('0 survived, 1 failed')
})

it('Example 3', () => {
  const noopRegistry: DriverRegistry = {
    developerProduct: {
      create: async () => ({ err: new Error('stub') as never, success: false }),
    },
    gamePass: {
      create: async () => ({ err: new Error('stub') as never, success: false }),
    },
    place: {
      create: async () => ({ err: new Error('stub') as never, success: false }),
    },
    universe: {
      create: async () => ({ err: new Error('stub') as never, success: false }),
    },
  }
  return applyOps([], noopRegistry).then((result) => {
    expect(result).toStrictEqual({ data: [], success: true })
  })
})
