// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  type ApplyError,
  applyOps,
  asRobloxAssetId,
  asSha256Hex,
  type DriverRegistry,
  type Operation,
} from 'bedrock'

it('Example 1', () => {
  function describe(err: ApplyError): string {
    switch (err.kind) {
      case 'driverFailure': {
        return `driver failed for ${err.key}: ${err.cause.message}`
      }
      case 'updateUnsupported': {
        return `update not yet supported for ${err.key}`
      }
    }
  }
  const err: ApplyError = {
    key: asResourceKey('vip-pass'),
    kind: 'updateUnsupported',
  }
  expect(describe(err)).toBe('update not yet supported for vip-pass')
})

it('Example 2', () => {
  const registry: DriverRegistry = {
    gamePass: {
      async create(desired) {
        return {
          data: {
            ...desired,
            outputs: {
              assetId: asRobloxAssetId('9876543210'),
              iconAssetId: asRobloxAssetId('1122334455'),
            },
          },
          success: true,
        }
      },
    },
  }
  const ops: ReadonlyArray<Operation> = [
    {
      key: asResourceKey('vip-pass'),
      type: 'create',
      desired: {
        key: asResourceKey('vip-pass'),
        name: 'VIP Pass',
        description: 'Grants VIP perks.',
        iconFileHash: asSha256Hex(
          'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        ),
        iconFilePath: 'assets/vip-icon.png',
        kind: 'gamePass',
        price: 500,
      },
    },
  ]
  return applyOps(ops, registry).then((result) => {
    expect(result).toStrictEqual({ data: undefined, success: true })
  })
})
