// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  type ApplyError,
  applyOps,
  asRobloxAssetId,
  asSha256Hex,
  type DriverRegistry,
  type Operation,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  function describe(err: ApplyError): string {
    switch (err.kind) {
      case 'driverFailure': {
        return `driver failed for ${err.key}: ${err.cause.message}`
      }
      case 'unexpectedThrow': {
        return `unexpected error for ${err.key}`
      }
      case 'updateUnsupported': {
        return `update not supported for ${err.key}`
      }
    }
  }
  const err: ApplyError = {
    key: asResourceKey('vip-pass'),
    kind: 'updateUnsupported',
  }
  expect(describe(err)).toBe('update not supported for vip-pass')
})

it('Example 2', () => {
  const registry: DriverRegistry = {
    gamePass: {
      async create(desired) {
        return {
          data: {
            ...desired,
            outputs: {
              assetId: asRobloxAssetId('9876543210'),
              iconAssetIds: { 'en-us': asRobloxAssetId('1122334455') },
            },
          },
          success: true,
        }
      },
    },
    place: {
      async create(desired) {
        return {
          data: { ...desired, outputs: { versionNumber: 1 } },
          success: true,
        }
      },
    },
    universe: {
      async create(desired) {
        return {
          data: {
            ...desired,
            outputs: { rootPlaceId: asRobloxAssetId('4711') },
          },
          success: true,
        }
      },
    },
    developerProduct: {
      async create(desired) {
        return {
          data: {
            ...desired,
            outputs: { productId: asRobloxAssetId('8172635495') },
          },
          success: true,
        }
      },
    },
  }
  const ops: ReadonlyArray<Operation> = [
    {
      key: asResourceKey('vip-pass'),
      type: 'create',
      desired: {
        key: asResourceKey('vip-pass'),
        name: 'VIP Pass',
        description: 'Grants VIP perks.',
        icon: { 'en-us': 'assets/vip-icon.png' },
        iconFileHashes: {
          'en-us': asSha256Hex(
            'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
          ),
        },
        kind: 'gamePass',
        price: 500,
      },
    },
  ]
  return applyOps(ops, registry).then((result) => {
    expect(result.success).toBe(true)
    expect(result.success && result.data).toHaveLength(1)
  })
})
