// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { asResourceKey, type BuildDesiredError, buildDesired } from 'bedrock'

it('Example 1', () => {
  const err: BuildDesiredError = {
    iconFilePath: 'assets/vip-icon.png',
    key: asResourceKey('vip-pass'),
    kind: 'iconReadFailed',
    reason: 'ENOENT',
  }
  expect(err.kind).toBe('iconReadFailed')
})

it('Example 2', () => {
  async function readFile(): Promise<Uint8Array> {
    return new Uint8Array([1, 2, 3])
  }
  return buildDesired(
    [
      {
        description: 'Grants VIP perks.',
        iconFilePath: 'assets/vip-icon.png',
        key: asResourceKey('vip-pass'),
        kind: 'gamePass',
        name: 'VIP Pass',
        price: 500,
      },
    ],
    readFile,
  ).then((result) => {
    expect(result.success).toBeTrue()
    if (result.success) {
      expect(result.data).toHaveLength(1)
      expect(result.data[0]!.kind).toBe('gamePass')
    }
  })
})
