// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  type GamePassConfigInput,
  type Slice1ConfigInput,
  type BuildDesiredError,
  buildDesired,
} from 'bedrock'

it('Example 1', () => {
  const entry: GamePassConfigInput = {
    description: 'Grants VIP perks.',
    iconFilePath: 'assets/vip-icon.png',
    key: 'vip-pass',
    name: 'VIP Pass',
    price: 500,
  }
  expect(entry.key).toBe('vip-pass')
})

it('Example 2', () => {
  const config: Slice1ConfigInput = {
    gamePasses: [
      {
        description: 'Grants VIP perks.',
        iconFilePath: 'assets/vip-icon.png',
        key: 'vip-pass',
        name: 'VIP Pass',
        price: 500,
      },
    ],
  }
  expect(config.gamePasses).toHaveLength(1)
})

it('Example 3', () => {
  function describe(err: BuildDesiredError): string {
    switch (err.kind) {
      case 'iconReadFailed': {
        return `icon read failed for ${err.key}: ${err.reason}`
      }
      case 'invalidKey': {
        return `invalid key: ${err.rawKey}`
      }
    }
  }
  const err: BuildDesiredError = { kind: 'invalidKey', rawKey: 'BAD KEY' }
  expect(describe(err)).toBe('invalid key: BAD KEY')
})

it('Example 4', () => {
  const readFile = async (): Promise<Uint8Array> => new Uint8Array([1, 2, 3])
  return buildDesired(
    {
      gamePasses: [
        {
          key: 'vip-pass',
          name: 'VIP Pass',
          description: 'Grants VIP perks.',
          iconFilePath: 'assets/vip-icon.png',
          price: 500,
        },
      ],
    },
    readFile,
  ).then((result) => {
    expect(result.success).toBeTrue()
    if (result.success) {
      expect(result.data).toHaveLength(1)
      expect(result.data[0]!.kind).toBe('gamePass')
    }
  })
})
