// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { buildStatePort } from '@bedrock/core'

it('Example 1', () => {
  const port = buildStatePort({
    fetch: async () =>
      new Response(JSON.stringify({ files: {} }), { status: 200 }),
    getEnv: (name) => (name === 'GITHUB_TOKEN' ? 'ghp_example' : undefined),
    stateConfig: { backend: 'gist', gistId: 'abc123' },
  })
  expect(port.success).toBeTrue()
})
