// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { buildStateBackend, buildStatePort } from '@bedrock-rbx/core'

it('Example 1', () => {
  const backend = buildStateBackend({
    fetch: async () =>
      new Response(JSON.stringify({ files: {} }), { status: 200 }),
    getEnv: (name) =>
      name === 'BEDROCK_GITHUB_TOKEN' ? 'ghp_example' : undefined,
    stateConfig: { backend: 'gist', gistId: 'abc123' },
  })
  expect(backend.success).toBeTrue()
  if (backend.success) {
    expect(backend.data.stateLockPort).toBeUndefined()
  }
})

it('Example 2', () => {
  const port = buildStatePort({
    fetch: async () =>
      new Response(JSON.stringify({ files: {} }), { status: 200 }),
    getEnv: (name) =>
      name === 'BEDROCK_GITHUB_TOKEN' ? 'ghp_example' : undefined,
    stateConfig: { backend: 'gist', gistId: 'abc123' },
  })
  expect(port.success).toBeTrue()
})
