// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  type MissingCredentialError,
  type UnsupportedBackendError,
  buildStatePort,
} from '@bedrock/core'

it('Example 1', () => {
  const err: MissingCredentialError = {
    kind: 'missingCredential',
    purpose: 'stateBackend',
    variable: 'GITHUB_TOKEN',
  }
  expect(err.kind).toBe('missingCredential')
})

it('Example 2', () => {
  const err: UnsupportedBackendError = {
    backend: 's3',
    hint: 'pass a custom statePort via opts.statePort',
    kind: 'unsupportedBackend',
  }
  expect(err.kind).toBe('unsupportedBackend')
})

it('Example 3', () => {
  const port = buildStatePort({
    fetch: async () =>
      new Response(JSON.stringify({ files: {} }), { status: 200 }),
    getEnv: (name) => (name === 'GITHUB_TOKEN' ? 'ghp_example' : undefined),
    stateConfig: { backend: 'gist', gistId: 'abc123' },
  })
  expect(port.success).toBeTrue()
})
