// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { type RegistryConfigError, buildDefaultRegistry } from '@bedrock/core'

it('Example 1', () => {
  const err: RegistryConfigError = {
    hint: 'declare universe.universeId in bedrock.config.ts',
    kind: 'registryConfigMissing',
    missing: 'universeId',
  }
  expect(err.kind).toBe('registryConfigMissing')
})

it('Example 2', () => {
  const registry = buildDefaultRegistry({
    config: {
      state: { backend: 'gist', gistId: 'abc' },
      universe: { universeId: '1234567890' },
    },
    getEnv: () => 'rbx-test',
    readFile: async () => new Uint8Array(),
  })
  expect(registry.success).toBeTrue()
})
