// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { defineConfig } from 'bedrock'

it('Example 1', () => {
  const config = defineConfig({
    passes: {
      'vip-pass': {
        description: 'Grants VIP perks.',
        iconFilePath: 'assets/vip-icon.png',
        name: 'VIP Pass',
        price: 500,
      },
    },
  })
  expect(config.passes!['vip-pass']!.name).toBe('VIP Pass')
})
