// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { defineConfig } from '@bedrock/core/config'

it('Example 1', () => {
  const config = defineConfig({
    environments: { production: {} },
    passes: {
      'vip-pass': {
        description: 'Grants VIP perks.',
        icon: { 'en-us': 'assets/vip-icon.png' },
        name: 'VIP Pass',
        price: 500,
      },
    },
  })
  expect(config.passes!['vip-pass']!.name).toBe('VIP Pass')
})
