// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  type BuildStep,
  deploy,
  type BedrockState,
  type DriverRegistry,
  type StatePort,
  provision,
  publish,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const built: Array<string> = []
  const build: BuildStep = ({ environment }) => {
    built.push(`build places/start.rbxl for ${environment}`)
  }
  return Promise.resolve(build({ environment: 'production' })).then(() => {
    expect(built).toStrictEqual(['build places/start.rbxl for production'])
  })
})

it('Example 2', () => {
  return deploy({ environment: 'production' }).then((result) => {
    expect(result.success).toBeFalse()
    if (!result.success) {
      expect(['configLoadFailed', 'stateNotConfigured']).toContain(
        result.err.kind,
      )
    }
  })
})

it('Example 3', () => {
  const store = new Map<string, BedrockState>()
  const statePort: StatePort = {
    async read(environment) {
      const state = store.get(environment)
      return { data: state === undefined ? {} : { state }, success: true }
    },
    async write(state) {
      store.set(state.environment, state)
      return { data: undefined, success: true }
    },
  }
  const registry: DriverRegistry = {
    developerProduct: {
      create: async () => {
        throw new Error('unreachable: empty config')
      },
    },
    gamePass: {
      create: async () => {
        throw new Error('unreachable: empty config')
      },
    },
    place: {
      create: async () => {
        throw new Error('unreachable: empty config')
      },
    },
    universe: {
      create: async () => {
        throw new Error('unreachable: empty config')
      },
    },
  }
  return deploy({
    config: {
      environments: { production: {} },
      state: { backend: 'gist', gistId: 'abc' },
      passes: {},
    },
    environment: 'production',
    registry,
    statePort,
  }).then((result) => {
    expect(result.success).toBeTrue()
    if (result.success) {
      expect(result.data.environment).toBe('production')
      expect(result.data.resources).toBeEmpty()
    }
  })
})

it('Example 4', () => {
  return provision({ environment: 'production' }).then((result) => {
    expect(result.success).toBeFalse()
    if (!result.success) {
      expect(['configLoadFailed', 'stateNotConfigured']).toContain(
        result.err.kind,
      )
    }
  })
})

it('Example 5', () => {
  return publish({ environment: 'production' }).then((result) => {
    expect(result.success).toBeFalse()
    if (!result.success) {
      expect(['configLoadFailed', 'stateNotConfigured']).toContain(
        result.err.kind,
      )
    }
  })
})
