// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  deploy,
  type BedrockState,
  type DriverRegistry,
  type StatePort,
} from '@bedrock/core'

it('Example 1', () => {
  return deploy({ environment: 'production' }).then((result) => {
    expect(result.success).toBeFalse()
    if (!result.success) {
      expect(['configLoadFailed', 'stateNotConfigured']).toContain(
        result.err.kind,
      )
    }
  })
})

it('Example 2', () => {
  const store = new Map<string, BedrockState>()
  const statePort: StatePort = {
    async read(environment) {
      return { data: store.get(environment), success: true }
    },
    async write(state) {
      store.set(state.environment, state)
      return { data: undefined, success: true }
    },
  }
  const registry: DriverRegistry = {
    developerProduct: {
      create: async () => {
        throw new Error('unreachable: empty config')
      },
    },
    gamePass: {
      create: async () => {
        throw new Error('unreachable: empty config')
      },
    },
    place: {
      create: async () => {
        throw new Error('unreachable: empty config')
      },
    },
    universe: {
      create: async () => {
        throw new Error('unreachable: empty config')
      },
    },
  }
  return deploy({
    config: {
      environments: { production: {} },
      state: { backend: 'gist', gistId: 'abc' },
      passes: {},
    },
    environment: 'production',
    registry,
    statePort,
  }).then((result) => {
    expect(result.success).toBeTrue()
    if (result.success) {
      expect(result.data.environment).toBe('production')
      expect(result.data.resources).toBeEmpty()
    }
  })
})
