// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { forceReleaseStateLockAsync } from '@bedrock-rbx/core'

it('Example 1', () => {
  return forceReleaseStateLockAsync({
    config: {
      environments: { production: {} },
      state: { backend: 'gist', gistId: 'abc123' },
    },
    environment: 'production',
    getEnv: () => 'ghp_example',
  }).then((released) => {
    expect(released.success).toBeTrue()
    if (released.success) {
      expect(released.data.locking).toBe('none')
    }
  })
})
