// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { loadConfig } from '@bedrock-rbx/core'

it('Example 1', () => {
  return loadConfig({
    configFile: 'bedrock.staging.config.yaml',
    cwd: '/path/that/does/not/have/a/config',
  }).then((result) => {
    expect(result.success).toBeFalse()
    if (!result.success) {
      expect(result.err.kind).toBe('fileNotFound')
    }
  })
})
