// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { loadConfig } from '@bedrock/core'

it('Example 1', () => {
  return loadConfig({ cwd: '/path/that/does/not/have/a/config' }).then(
    (result) => {
      expect(result.success).toBeFalse()
      if (!result.success) {
        expect(result.err.kind).toBe('fileNotFound')
      }
    },
  )
})
