// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { migrateMantleState } from '@bedrock/core'

it('Example 1', () => {
  const yaml = [
    'version: "6"',
    'environments:',
    '  production:',
    '    - id: experience_singleton',
    '      inputs:',
    '        experience:',
    '          groupId: ~',
    '      outputs:',
    '        experience:',
    '          assetId: 6031475575',
    '          startPlaceId: 17613681043',
    '      dependencies: []',
    '',
  ].join('\n')
  async function readFile(): Promise<Uint8Array> {
    return new TextEncoder().encode(yaml)
  }
  return migrateMantleState({
    outputFormat: 'typescript',
    readFile,
    stateFilePath: '.mantle-state.yml',
  }).then((result) => {
    expect(result.success).toBeTrue()
    if (result.success) {
      expect(Object.keys(result.data.config.environments)).toStrictEqual([
        'production',
      ])
    }
  })
})
