// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { moveStateAsync } from '@bedrock-rbx/core'

it('Example 1', () => {
  return moveStateAsync(
    {
      fetch: async () =>
        new Response(JSON.stringify({ files: {} }), { status: 200 }),
      getEnv: () => 'ghp_example',
    },
    {
      config: {
        environments: { production: {} },
        state: { backend: 'gist', gistId: 'source-gist' },
      },
      destination: { backend: 'gist', gistId: 'destination-gist' },
      dryRun: false,
      environments: ['production'],
      force: false,
    },
  ).then((moved) => {
    expect(moved.success).toBeTrue()
    if (moved.success) {
      expect(moved.data.moved).toBeEmpty()
      expect(moved.data.decisions.get('production')).toStrictEqual({
        kind: 'skip',
        reason: 'sourceEmpty',
      })
    }
  })
})
