// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { createClackProgressAdapter, type ClackPort } from '@bedrock-rbx/core'

it('Example 1', () => {
  const lines: Array<string> = []
  const clack: ClackPort = {
    cancel: (message) => lines.push(`cancel: ${message}`),
    intro: (message) => lines.push(`intro: ${message}`),
    logError: (message) => lines.push(`error: ${message}`),
    logMessage: (message) => lines.push(`log: ${message}`),
    logSuccess: (message) => lines.push(`ok: ${message}`),
    outro: (message) => lines.push(`outro: ${message}`),
  }
  const port = createClackProgressAdapter({ clack })
  port.emit({
    environment: 'production',
    kind: 'deploySuccess',
    resourceCount: 3,
  })
  expect(lines).toEqual(['ok: production: 3 resources reconciled'])
})
