// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { HttpClient } from '@bedrock/ocale'
import { DeveloperProductsClient } from '@bedrock/ocale/developer-products'
import {
  asRobloxAssetId,
  type DeveloperProductDriverDeps,
  asResourceKey,
  createDeveloperProductDriver,
} from '@bedrock/core'

it('Example 1', () => {
  const httpClient: HttpClient = {
    async request() {
      return { data: { body: {}, headers: {}, status: 200 }, success: true }
    },
  }
  const deps: DeveloperProductDriverDeps = {
    client: new DeveloperProductsClient({
      apiKey: 'rbx-your-key',
      httpClient,
      sleep: async () => {},
    }),
    readFile: async () => new Uint8Array([137, 80, 78, 71]),
    universeId: asRobloxAssetId('1234567890'),
  }
  expect(deps.universeId).toBe('1234567890')
})

it('Example 2', () => {
  const httpClient: HttpClient = {
    async request() {
      return {
        data: {
          body: {
            createdTimestamp: '2024-01-15T10:30:00.000Z',
            description: 'Stocks the player up with 1,000 premium gems.',
            iconImageAssetId: null,
            isForSale: false,
            isImmutable: false,
            name: 'Gem Pack',
            priceInformation: null,
            productId: 9876543210,
            storePageEnabled: false,
            universeId: 1234567890,
            updatedTimestamp: '2024-01-15T10:30:00.000Z',
          },
          headers: {},
          status: 200,
        },
        success: true,
      }
    },
  }
  const driver = createDeveloperProductDriver({
    client: new DeveloperProductsClient({
      apiKey: 'rbx-your-key',
      httpClient,
      sleep: async () => {},
    }),
    readFile: async () => new Uint8Array([137, 80, 78, 71]),
    universeId: asRobloxAssetId('1234567890'),
  })
  return driver
    .create({
      description: 'Stocks the player up with 1,000 premium gems.',
      key: asResourceKey('gem-pack'),
      kind: 'developerProduct',
      name: 'Gem Pack',
      price: undefined,
    })
    .then((result) => {
      expect(result.success).toBeTrue()
      if (result.success) {
        expect(result.data.outputs.productId).toBe('9876543210')
      }
    })
})
