// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { createFsCodegenWriter } from '@bedrock-rbx/core'

it('Example 1', () => {
  const writes: Array<{
    content: string
    path: string
  }> = []
  const writer = createFsCodegenWriter({
    mkdir: async () => undefined,
    outputDir: 'src/generated',
    writeFile: async (path, content) => {
      writes.push({ content, path })
    },
  })
  return writer
    .write({ content: 'return {}\n', path: 'ids.luau' })
    .then((result) => {
      expect(result.success).toBeTrue()
      expect(writes[0]?.content).toBe('return {}\n')
      expect(writes[0]?.path).toContain('ids.luau')
    })
})
