// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { HttpClient } from '@bedrock/ocale'
import { GamePassesClient } from '@bedrock/ocale/game-passes'
import {
  asRobloxAssetId,
  type GamePassDriverDeps,
  asResourceKey,
  asSha256Hex,
  createGamePassDriver,
} from '@bedrock/core'

it('Example 1', () => {
  const httpClient: HttpClient = {
    async request() {
      return { data: { body: {}, headers: {}, status: 200 }, success: true }
    },
  }
  const deps: GamePassDriverDeps = {
    client: new GamePassesClient({
      apiKey: 'rbx-your-key',
      httpClient,
      sleep: async () => {},
    }),
    readFile: async () => new Uint8Array([137, 80, 78, 71]),
    universeId: asRobloxAssetId('1234567890'),
  }
  expect(deps.universeId).toBe('1234567890')
})

it('Example 2', () => {
  const httpClient: HttpClient = {
    async request() {
      return {
        data: {
          body: {
            createdTimestamp: '2024-01-15T10:30:00.000Z',
            description: 'Grants VIP perks.',
            gamePassId: 9876543210,
            iconAssetId: 1122334455,
            isForSale: true,
            name: 'VIP Pass',
            updatedTimestamp: '2024-01-15T10:30:00.000Z',
          },
          headers: {},
          status: 200,
        },
        success: true,
      }
    },
  }
  const driver = createGamePassDriver({
    client: new GamePassesClient({
      apiKey: 'rbx-your-key',
      httpClient,
      sleep: async () => {},
    }),
    readFile: async () => new Uint8Array([137, 80, 78, 71]),
    universeId: asRobloxAssetId('1234567890'),
  })
  return driver
    .create({
      description: 'Grants VIP perks.',
      icon: { 'en-us': 'assets/vip-icon.png' },
      iconFileHashes: {
        'en-us': asSha256Hex(
          'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        ),
      },
      key: asResourceKey('vip-pass'),
      kind: 'gamePass',
      name: 'VIP Pass',
      price: 500,
    })
    .then((result) => {
      expect(result.success).toBeTrue()
      if (result.success) {
        expect(result.data.outputs.assetId).toBe('9876543210')
      }
    })
})
