// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  type GistStateAdapterDeps,
  createGistStateAdapter,
} from '@bedrock/core'

it('Example 1', () => {
  const deps: GistStateAdapterDeps = {
    gistId: 'abc123def456',
    token: 'ghp_example',
  }
  expect(deps.gistId).toBe('abc123def456')
})

it('Example 2', () => {
  const port = createGistStateAdapter({
    fetch: async () =>
      new Response(JSON.stringify({ files: {} }), { status: 200 }),
    gistId: 'abc123def456',
    token: 'ghp_example',
  })
  return port.read('production').then((result) => {
    expect(result.success).toBeTrue()
    if (result.success) {
      expect(result.data).toBeUndefined()
    }
  })
})
