// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { createGistStateAdapter } from '@bedrock-rbx/core'

it('Example 1', () => {
  const port = createGistStateAdapter({
    fetch: async () =>
      new Response(JSON.stringify({ files: {} }), { status: 200 }),
    gistId: 'abc123def456',
    token: 'ghp_example',
  })
  return port.read('production').then((result) => {
    expect(result.success).toBeTrue()
    if (result.success) {
      expect(result.data).toBeUndefined()
    }
  })
})
