// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { createNoOpProgressAdapter } from '@bedrock-rbx/core'

it('Example 1', () => {
  const port = createNoOpProgressAdapter()
  expect(() =>
    port.emit({
      environment: 'production',
      kind: 'deploySuccess',
      resourceCount: 3,
    }),
  ).not.toThrow()
})
