// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { HttpClient } from '@bedrock-rbx/ocale'
import { PlacesClient } from '@bedrock-rbx/ocale/places'
import {
  asRobloxAssetId,
  type PlaceDriverDeps,
  asResourceKey,
  asSha256Hex,
  createPlaceDriver,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const httpClient: HttpClient = {
    async request() {
      return { data: { body: {}, headers: {}, status: 200 }, success: true }
    },
  }
  const deps: PlaceDriverDeps = {
    client: new PlacesClient({
      apiKey: 'rbx-your-key',
      httpClient,
      sleep: async () => {},
    }),
    readFile: async () => new Uint8Array(),
    universeId: asRobloxAssetId('1234567890'),
  }
  expect(deps.universeId).toBe('1234567890')
})

it('Example 2', () => {
  const httpClient: HttpClient = {
    async request() {
      return {
        data: { body: { versionNumber: 1 }, headers: {}, status: 200 },
        success: true,
      }
    },
  }
  const driver = createPlaceDriver({
    client: new PlacesClient({
      apiKey: 'rbx-your-key',
      httpClient,
      sleep: async () => {},
    }),
    readFile: async () =>
      new Uint8Array([
        60, 114, 111, 98, 108, 111, 120, 33, 137, 255, 13, 10, 26, 10,
      ]),
    universeId: asRobloxAssetId('1234567890'),
  })
  return driver
    .create({
      description: undefined,
      displayName: undefined,
      fileHash: asSha256Hex(
        'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      ),
      filePath: 'places/start.rbxl',
      key: asResourceKey('start-place'),
      kind: 'place',
      placeId: asRobloxAssetId('4711'),
      serverSize: undefined,
    })
    .then((result) => {
      expect(result.success).toBeTrue()
      if (result.success) {
        expect(result.data.outputs.versionNumber).toBe(1)
      }
    })
})
