// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { HttpClient } from '@bedrock/ocale'
import { ExperienceIconClient } from '@bedrock/ocale/experience-icon'
import { PlacesClient } from '@bedrock/ocale/places'
import { UniversesClient } from '@bedrock/ocale/universes'
import { validUniverseBody } from '@bedrock/ocale/testing'
import {
  asRobloxAssetId,
  createUniverseDriver,
  UNIVERSE_SINGLETON_KEY,
} from '@bedrock/core'

it('Example 1', () => {
  const universeBodyHttpClient: HttpClient = {
    async request() {
      return {
        data: {
          body: validUniverseBody({
            path: 'universes/1234567890',
            rootPlace: 'universes/1234567890/places/4711',
          }),
          headers: {},
          status: 200,
        },
        success: true,
      }
    },
  }
  const driver = createUniverseDriver({
    experienceIcons: new ExperienceIconClient({
      apiKey: 'rbx-your-key',
      httpClient: universeBodyHttpClient,
      sleep: async () => {},
    }),
    places: new PlacesClient({
      apiKey: 'rbx-your-key',
      httpClient: universeBodyHttpClient,
      sleep: async () => {},
    }),
    readFile: async () => new Uint8Array(),
    universes: new UniversesClient({
      apiKey: 'rbx-your-key',
      httpClient: universeBodyHttpClient,
      sleep: async () => {},
    }),
  })
  return driver
    .create({
      consoleEnabled: undefined,
      desktopEnabled: true,
      displayName: undefined,
      key: UNIVERSE_SINGLETON_KEY,
      kind: 'universe',
      mobileEnabled: undefined,
      privateServerPriceRobux: undefined,
      tabletEnabled: undefined,
      universeId: asRobloxAssetId('1234567890'),
      visibility: 'public',
      voiceChatEnabled: true,
      vrEnabled: undefined,
    })
    .then((result) => {
      expect(result.success).toBeTrue()
      if (result.success) {
        expect(result.data.outputs.rootPlaceId).toBe('4711')
      }
    })
})
