// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { UniversesClient } from '@bedrock/ocale/universes'
import { validUniverseBody } from '@bedrock/ocale/testing'
import {
  asRobloxAssetId,
  createUniverseDriver,
  UNIVERSE_SINGLETON_KEY,
} from '@bedrock/core'

it('Example 1', () => {
  const driver = createUniverseDriver({
    client: new UniversesClient({
      apiKey: 'rbx-your-key',
      httpClient: {
        async request() {
          return {
            data: {
              body: validUniverseBody({
                path: 'universes/1234567890',
                rootPlace: 'universes/1234567890/places/4711',
              }),
              headers: {},
              status: 200,
            },
            success: true,
          }
        },
      },
      sleep: async () => {},
    }),
  })
  return driver
    .create({
      key: UNIVERSE_SINGLETON_KEY,
      kind: 'universe',
      universeId: asRobloxAssetId('1234567890'),
      voiceChatEnabled: true,
    })
    .then((result) => {
      expect(result.success).toBeTrue()
      if (result.success) {
        expect(result.data.outputs.rootPlaceId).toBe('4711')
      }
    })
})
