// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { HttpClient } from '@bedrock/ocale'
import { UniversesClient } from '@bedrock/ocale/universes'
import {
  type UniverseDriverDeps,
  asRobloxAssetId,
  createUniverseDriver,
  UNIVERSE_SINGLETON_KEY,
} from 'bedrock'

it('Example 1', () => {
  const httpClient: HttpClient = {
    async request() {
      return { data: { body: {}, headers: {}, status: 200 }, success: true }
    },
  }
  const deps: UniverseDriverDeps = {
    client: new UniversesClient({
      apiKey: 'rbx-your-key',
      httpClient,
      sleep: async () => {},
    }),
  }
  expect(deps.client).toBeInstanceOf(UniversesClient)
})

it('Example 2', () => {
  const universeBody = {
    ageRating: 'AGE_RATING_13_PLUS',
    consoleEnabled: false,
    createTime: '2024-01-15T10:30:00.000Z',
    description: 'A sample universe.',
    desktopEnabled: true,
    displayName: 'Test Universe',
    mobileEnabled: true,
    path: 'universes/1234567890',
    rootPlace: 'universes/1234567890/places/4711',
    tabletEnabled: true,
    updateTime: '2024-11-02T17:08:21.500Z',
    user: 'users/7777',
    visibility: 'PUBLIC' as const,
    voiceChatEnabled: false,
    vrEnabled: false,
  }
  const httpClient: HttpClient = {
    async request() {
      return {
        data: { body: universeBody, headers: {}, status: 200 },
        success: true,
      }
    },
  }
  const driver = createUniverseDriver({
    client: new UniversesClient({
      apiKey: 'rbx-your-key',
      httpClient,
      sleep: async () => {},
    }),
  })
  return driver
    .create({
      key: UNIVERSE_SINGLETON_KEY,
      kind: 'universe',
      universeId: asRobloxAssetId('1234567890'),
      voiceChatEnabled: true,
    })
    .then((result) => {
      expect(result.success).toBeTrue()
      if (result.success) {
        expect(result.data.outputs.rootPlaceId).toBe('4711')
      }
    })
})
