// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { asResourceKey, asSha256Hex, type GamePassDesiredState } from 'bedrock'

it('Example 1', () => {
  const pass: GamePassDesiredState = {
    description: 'Grants VIP perks.',
    iconFileHash: asSha256Hex(
      'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    ),
    iconFilePath: 'assets/vip-icon.png',
    key: asResourceKey('vip-pass'),
    kind: 'gamePass',
    name: 'VIP Pass',
    price: undefined,
  }
  expect(pass.kind).toBe('gamePass')
  expect(pass.price).toBeUndefined()
})
