import { codegenViewOf, findResource, realValue } from "@bedrock-rbx/core";
import type {
	BedrockState,
	CodegenFile,
	EmitInput,
	Emitter,
	ResourceCurrentState,
	ResourceKey,
} from "@bedrock-rbx/core";

// Custom codegen emitter. The built-in one writes a Luau table of ids; this one
// generates TypeScript: an enum of universe ids, and one table per resource
// kind keyed by config key then by environment, so game code resolves an id
// from `game.GameId` at runtime and one built place serves every environment.
//
// An emitter is a pure function of the deploy state, so it unit-tests without
// any fixtures beyond a state object.

const HEADER = "// Generated by bedrock. Do not edit by hand.";
const OUTPUT_PATH = "resources.ts";

type ProvisionedKind = "developerProduct" | "gamePass";

interface ResolvedEnvironment {
	readonly memberName: string;
	readonly state: BedrockState;
	readonly universeId: string;
}

interface TableSpec {
	readonly exportName: string;
	readonly kind: ProvisionedKind;
	/** Doc comment written above the exported table. */
	readonly summary: string;
}

/** One exported table, and the environments it is rendered from. */
interface Table extends TableSpec {
	readonly environments: ReadonlyArray<ResolvedEnvironment>;
}

/** Fixed type surface every generated file carries, independent of state. */
const TYPE_DECLARATIONS: ReadonlyArray<string> = [
	"/** One provisioned resource, as deployed to one environment. */",
	"export interface ResourceMetadata {",
	"\treadonly name: string;",
	"\treadonly price: number | undefined;",
	"\treadonly assetId: number;",
	"}",
	"",
	"type ResourceTable = Record<string, Partial<Record<GameId, ResourceMetadata>>>;",
	"",
];

const TABLES = [
	{
		exportName: "GAME_PASSES",
		kind: "gamePass",
		summary: "Game passes, keyed by config key then by universe.",
	},
	{
		exportName: "PRODUCTS",
		kind: "developerProduct",
		summary: "Developer products, keyed by config key then by universe.",
	},
] as const satisfies ReadonlyArray<TableSpec>;

function pascalCase(value: string): string {
	return value
		.split("-")
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("");
}

function resolveEnvironments(
	environments: EmitInput["environments"],
): ReadonlyArray<ResolvedEnvironment> {
	return Object.keys(environments)
		.toSorted()
		.flatMap((name) => {
			const state = environments[name];
			const universe = state && findResource(state.resources, { kind: "universe" });
			// Bedrock hands the emitter every environment declared in the
			// config, deployed or not. One that has never deployed has no
			// universe resource, so it is dropped rather than emitted as an
			// enum member with no id behind it.
			if (!state || universe === undefined) {
				return [];
			}

			return [{ memberName: pascalCase(name), state, universeId: universe.universeId }];
		});
}

function entryLines({ environments, kind }: Table, key: ResourceKey): ReadonlyArray<string> {
	const perEnvironment = environments.flatMap((environment) => {
		const resource: ResourceCurrentState<ProvisionedKind> | undefined = findResource(
			environment.state.resources,
			{ key, kind },
		);
		// A key never deployed to this environment, or whose create failed on
		// the last run, is absent from the record — which is why the generated
		// type is a `Partial`.
		if (resource === undefined) {
			return [];
		}

		// `codegenViewOf` reads through redaction: `realValue` returns what the
		// config declared, not the placeholder bedrock pushed to Roblox.
		const view = codegenViewOf(environment.state, resource);
		const assetId =
			resource.kind === "developerProduct"
				? resource.outputs.productId
				: resource.outputs.assetId;

		return [
			`\t\t[GameId.${environment.memberName}]: {`,
			`\t\t\tname: ${JSON.stringify(realValue(view.name))},`,
			// `undefined` is bedrock's off-sale state, not a missing value, so
			// it is emitted verbatim rather than coalesced to a price of zero.
			`\t\t\tprice: ${realValue(view.price) ?? "undefined"},`,
			`\t\t\tassetId: ${assetId},`,
			"\t\t},",
		];
	});

	return [`\t${JSON.stringify(key)}: {`, ...perEnvironment, "\t},"];
}

function tableLines(table: Table): ReadonlyArray<string> {
	const keys = new Set(
		table.environments
			.flatMap((environment) => environment.state.resources)
			.filter((resource) => resource.kind === table.kind)
			.map((resource) => resource.key),
	);

	return [
		`/** ${table.summary} */`,
		`export const ${table.exportName} = {`,
		...[...keys].toSorted().flatMap((key) => entryLines(table, key)),
		"} as const satisfies ResourceTable;",
		"",
	];
}

function emitResources(input: EmitInput): ReadonlyArray<CodegenFile> {
	const environments = resolveEnvironments(input.environments);
	const lines: ReadonlyArray<string> = [
		HEADER,
		"",
		"/** Universe id of every environment that has been deployed at least once. */",
		"export enum GameId {",
		...environments.map(
			(environment) => `\t${environment.memberName} = ${environment.universeId},`,
		),
		"}",
		"",
		...TYPE_DECLARATIONS,
		...TABLES.flatMap((table) => tableLines({ ...table, environments })),
	];

	// Paths are relative to `codegen.output`.
	return [{ content: `${lines.join("\n").trimEnd()}\n`, path: OUTPUT_PATH }];
}

/** Emitter passed to `deploy()` in `.bedrock/deploy.ts`. */
export const emit: Emitter = emitResources;
