import { codegenViewOf, findResource, realValue } from "@bedrock-rbx/core";
import type {
	BedrockState,
	CodegenFile,
	EmitInput,
	Emitter,
	ResourceCurrentState,
	ResourceKey,
} from "@bedrock-rbx/core";

/**
 * Custom codegen emitter.
 *
 * The built-in emitter writes a Luau table of ids. This one generates
 * TypeScript for a roblox-ts project instead: an enum of universe ids, and one
 * table per provisioned kind keyed by config key then by environment, so game
 * code resolves an id from `game.GameId` at runtime and one built place serves
 * every environment.
 *
 * An emitter is a pure function of the deploy state — same state in, same
 * files out — so it is the natural thing to unit-test in your own project.
 */

const HEADER = "// Generated by bedrock. Do not edit by hand.";
const OUTPUT_PATH = "resources.ts";

/** Environments, keyed by name, exactly as bedrock hands them to an emitter. */
type Environments = EmitInput["environments"];

type ProvisionedKind = "developerProduct" | "gamePass";

interface ResolvedEnvironment {
	/** Enum member name generated for this environment. */
	readonly memberName: string;
	/** Deployed state of this environment. */
	readonly state: BedrockState;
	/** Universe id backing the enum member. */
	readonly universeId: string;
}

function pascalCase(value: string): string {
	return value
		.split("-")
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("");
}

/**
 * Resolves the environments that contribute to the generated file.
 *
 * Bedrock hands the emitter every environment declared in the config — fresh
 * state for the one being deployed, last-known state for the rest. An
 * environment that has never deployed has no universe resource yet, so it is
 * dropped rather than emitted as an enum member with no id behind it.
 *
 * @param environments - Per-environment deploy state, keyed by environment name.
 * @returns The contributing environments, in name order.
 */
function resolveEnvironments(environments: Environments): ReadonlyArray<ResolvedEnvironment> {
	return Object.keys(environments)
		.toSorted()
		.flatMap((name) => {
			const state = environments[name];
			if (state === undefined) {
				return [];
			}

			const universe = findResource(state.resources, { kind: "universe" });
			if (universe === undefined) {
				return [];
			}

			return [{ memberName: pascalCase(name), state, universeId: universe.universeId }];
		});
}

function collectKeys(
	environments: ReadonlyArray<ResolvedEnvironment>,
	kind: ProvisionedKind,
): ReadonlyArray<ResourceKey> {
	const keys = new Set<ResourceKey>();
	for (const environment of environments) {
		for (const resource of environment.state.resources) {
			if (resource.kind === kind) {
				keys.add(resource.key);
			}
		}
	}

	return [...keys].toSorted();
}

/**
 * Renders one config key as a per-environment record of metadata.
 *
 * A key with no resource in an environment — never deployed there, or its
 * create failed on the last run — is simply absent from that record, which is
 * why the generated type is a `Partial`.
 *
 * @param environments - The contributing environments.
 * @param kind - Resource kind being rendered.
 * @param key - Config key being rendered.
 * @returns The lines of the record entry.
 */
function entryLines(
	environments: ReadonlyArray<ResolvedEnvironment>,
	kind: ProvisionedKind,
	key: ResourceKey,
): ReadonlyArray<string> {
	const perEnvironment = environments.flatMap((environment) => {
		const resource: ResourceCurrentState<ProvisionedKind> | undefined = findResource(
			environment.state.resources,
			{ key, kind },
		);
		if (resource === undefined) {
			return [];
		}

		// `codegenViewOf` reads through redaction: `realValue` returns what the
		// config declared, not the placeholder bedrock pushed to Roblox.
		const view = codegenViewOf(environment.state, resource);

		return [
			`\t\t[GameId.${environment.memberName}]: {`,
			`\t\t\tname: ${JSON.stringify(realValue(view.name))},`,
			`\t\t\tprice: ${realValue(view.price) ?? 0},`,
			`\t\t\tassetId: ${resource.kind === "developerProduct" ? resource.outputs.productId : resource.outputs.assetId},`,
			"\t\t},",
		];
	});

	return [`\t${JSON.stringify(key)}: {`, ...perEnvironment, "\t},"];
}

function tableLines(
	environments: ReadonlyArray<ResolvedEnvironment>,
	kind: ProvisionedKind,
	exportName: string,
	summary: string,
): ReadonlyArray<string> {
	return [
		`/** ${summary} */`,
		`export const ${exportName} = {`,
		...collectKeys(environments, kind).flatMap((key) => entryLines(environments, kind, key)),
		"} as const satisfies ResourceTable;",
		"",
	];
}

// The fixed type surface every generated file carries, independent of state.
const TYPE_DECLARATIONS: ReadonlyArray<string> = [
	"/** One provisioned resource, as deployed to one environment. */",
	"export interface ResourceMetadata {",
	"\treadonly name: string;",
	"\treadonly price: number;",
	"\treadonly assetId: number;",
	"}",
	"",
	"type ResourceTable = Record<string, Partial<Record<GameId, ResourceMetadata>>>;",
	"",
];

function generateResourceFile(environments: ReadonlyArray<ResolvedEnvironment>): CodegenFile {
	const lines: ReadonlyArray<string> = [
		HEADER,
		"",
		"/** Universe id of every environment declared in bedrock.config.ts. */",
		"export enum GameId {",
		...environments.map(
			(environment) => `\t${environment.memberName} = ${environment.universeId},`,
		),
		"}",
		"",
		...TYPE_DECLARATIONS,
		...tableLines(
			environments,
			"gamePass",
			"GAME_PASSES",
			"Game passes, keyed by config key then by universe.",
		),
		...tableLines(
			environments,
			"developerProduct",
			"PRODUCTS",
			"Developer products, keyed by config key then by universe.",
		),
	];

	return { content: `${lines.join("\n").trimEnd()}\n`, path: OUTPUT_PATH };
}

/**
 * Turns the deploy state of every declared environment into the generated
 * source files. Bedrock writes each returned file under `codegen.output`.
 *
 * @param input - Per-environment deploy state assembled by the deploy.
 * @returns The files to write, each path relative to `codegen.output`.
 */
function emitResources(input: EmitInput): ReadonlyArray<CodegenFile> {
	return [generateResourceFile(resolveEnvironments(input.environments))];
}

/** Emitter passed to `deploy()` in `.bedrock/deploy.ts`. */
export const emit: Emitter = emitResources;
