// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { findErrorCode, isTimeoutAbort } from './find-error-code'

it('Example 1', () => {
  const root = Object.assign(new Error('read ECONNRESET'), {
    code: 'ECONNRESET',
  })
  const outer = new Error('Network request failed', {
    cause: new TypeError('fetch failed', { cause: root }),
  })
  expect(findErrorCode(outer)).toBe('ECONNRESET')
})

it('Example 2', () => {
  const error = new Error('Network request failed', {
    cause: new DOMException('timed out', 'TimeoutError'),
  })
  expect(isTimeoutAbort(error)).toBe(true)
  expect(isTimeoutAbort(new DOMException('cancelled', 'AbortError'))).toBe(
    false,
  )
})
