// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { defaultKindRegistry } from '@bedrock-rbx/core'

it('Example 1', () => {
  expect(defaultKindRegistry.gamePass.kind).toBe('gamePass')
  expect(defaultKindRegistry.place.kind).toBe('place')
  expect(defaultKindRegistry.universe.kind).toBe('universe')
  expect(defaultKindRegistry.developerProduct.kind).toBe('developerProduct')
})
