// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  type BuildDesiredError,
  type KindIo,
  asSha256Hex,
  type ResourceKindModule,
} from '@bedrock/core'
import { type } from 'arktype'

it('Example 1', () => {
  const err: BuildDesiredError = {
    filePath: 'assets/vip-icon.png',
    key: asResourceKey('vip-pass'),
    kind: 'fileReadFailed',
    reason: 'ENOENT',
  }
  expect(err.kind).toBe('fileReadFailed')
})

it('Example 2', () => {
  const io: KindIo = {
    readFile: async () => new Uint8Array([1, 2, 3]),
  }
  expect(io.readFile).toBeFunction()
})

it('Example 3', () => {
  const stubKind: ResourceKindModule<'gamePass'> = {
    kind: 'gamePass',
    entrySchema: type({
      description: 'string',
      iconFilePath: 'string',
      name: 'string',
      'price?': 'number | undefined',
    }),
    flatten: () => [],
    normalize: async (input) => ({
      data: {
        description: input.description,
        iconFileHash: asSha256Hex(
          'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        ),
        iconFilePath: input.iconFilePath,
        key: input.key,
        kind: 'gamePass',
        name: input.name,
        price: input.price,
      },
      success: true,
    }),
    fieldsEqual: (desired, current) => desired.name === current.name,
  }
  expect(stubKind.kind).toBe('gamePass')
})
