// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { Result, Page } from '@bedrock-rbx/ocale'

it('Example 1', () => {
  function parseAge(input: string): Result<number, Error> {
    const age = Number(input)
    return Number.isFinite(age)
      ? { data: age, success: true }
      : { err: new Error(`Not a number: ${input}`), success: false }
  }
  const ok = parseAge('42')
  if (ok.success) {
    expect(ok.data).toBe(42)
  }
  const bad = parseAge('nope')
  if (!bad.success) {
    expect(bad.err.message).toContain('Not a number')
  }
})

it('Example 2', () => {
  const middle: Page<string> = { items: ['a', 'b'], nextPageToken: 'cursor' }
  expect(middle.items).toEqual(['a', 'b'])
  expect(middle.nextPageToken).toBe('cursor')
  const last: Page<string> = { items: ['c'], nextPageToken: undefined }
  expect(last.items).toEqual(['c'])
  expect(last.nextPageToken).toBeUndefined()
})
