// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { Result } from '@bedrock/ocale'

it('Example 1', () => {
  function parseAge(input: string): Result<number, Error> {
    const n = Number(input)
    return Number.isFinite(n)
      ? { data: n, success: true }
      : { err: new Error(`Not a number: ${input}`), success: false }
  }
  const ok = parseAge('42')
  if (ok.success) {
    expect(ok.data).toBe(42)
  }
  const bad = parseAge('nope')
  if (!bad.success) {
    expect(bad.err.message).toContain('Not a number')
  }
})
