// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { ExperienceIconClient } from '@bedrock/ocale/experience-icon'

it('Example 1', () => {
  const client = new ExperienceIconClient({ apiKey: 'your-key' })
  expect(client).toBeInstanceOf(ExperienceIconClient)
})
