// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { createClackPort } from '@bedrock-rbx/core'

it('Example 1', () => {
  const port = createClackPort()
  expect(typeof port.logSuccess).toBe('function')
})
