// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { createDefaultSpawner } from '@bedrock-rbx/core'
import process from 'node:process'

it('Example 1', () => {
  const spawner = createDefaultSpawner()
  return spawner
    .spawn({
      args: ['-e', 'process.exit(0)'],
      command: process.execPath,
      envOverrides: {},
    })
    .then((result) => {
      expect(result.success).toBeTrue()
      if (result.success) {
        expect(result.data).toBe(0)
      }
    })
})
