// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { dispatchOverride, type Spawner } from '@bedrock-rbx/core'

it('Example 1', () => {
  const spawner: Spawner = {
    async spawn() {
      return { data: 0, success: true }
    },
  }
  return dispatchOverride(
    {
      environment: 'production',
      overridePath: '/abs/.bedrock/deploy.ts',
    },
    spawner,
  ).then((result) => {
    expect(result.success).toBeTrue()
  })
})
