// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { type ClackPort, createClackPort } from '@bedrock-rbx/core'

it('Example 1', () => {
  const lines: Array<string> = []
  const port: ClackPort = {
    cancel: (message) => lines.push(`cancel: ${message}`),
    intro: (message) => lines.push(`intro: ${message}`),
    logError: (message) => lines.push(`error: ${message}`),
    logMessage: (message) => lines.push(`log: ${message}`),
    logSuccess: (message) => lines.push(`ok: ${message}`),
    outro: (message) => lines.push(`outro: ${message}`),
  }
  port.logSuccess('done')
  expect(lines).toEqual(['ok: done'])
})

it('Example 2', () => {
  const port = createClackPort()
  expect(typeof port.logSuccess).toBe('function')
})
