// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { Spawner, SpawnInvocation } from '@bedrock-rbx/core'

it('Example 1', () => {
  const invocations: Array<SpawnInvocation> = []
  const spawner: Spawner = {
    async spawn(invocation) {
      invocations.push(invocation)
      return { data: 0, success: true }
    },
  }
  return spawner
    .spawn({ args: ['--env', 'production'], command: 'bun', envOverrides: {} })
    .then((result) => {
      expect(result.success).toBeTrue()
      expect(invocations).toHaveLength(1)
    })
})
