// Generated by bedrock. Do not edit by hand.

/** Universe id of every environment that has been deployed at least once. */
export enum GameId {
	Development = 3218475960,
	Production = 3218475961,
}

/** One provisioned resource, as deployed to one environment. */
export interface ResourceMetadata {
	readonly name: string;
	readonly price: number | undefined;
	readonly assetId: number;
}

type ResourceTable = Record<string, Partial<Record<GameId, ResourceMetadata>>>;

/** Game passes, keyed by config key then by universe. */
export const GAME_PASSES = {
	"vip-pass": {
		[GameId.Development]: {
			name: "VIP Pass",
			price: 500,
			assetId: 1147203344,
		},
		[GameId.Production]: {
			name: "VIP Pass",
			price: 500,
			assetId: 1147203390,
		},
	},
} as const satisfies ResourceTable;

/** Developer products, keyed by config key then by universe. */
export const PRODUCTS = {
	"coins-small": {
		[GameId.Development]: {
			name: "100 Coins",
			price: 49,
			assetId: 2298471055,
		},
		[GameId.Production]: {
			name: "100 Coins",
			price: 49,
			assetId: 2298471088,
		},
	},
} as const satisfies ResourceTable;
