// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  createFetchHttpClient,
  type HttpClient,
  type HttpRequest,
} from '@bedrock-rbx/ocale'
import {
  type DeleteExperienceIconParameters,
  UniversesClient,
} from '@bedrock-rbx/ocale/universes'

it('Example 1', () => {
  const defaultHttpClient = createFetchHttpClient()
  let observedRequests: ReadonlyArray<HttpRequest> = []
  const tracedHttpClient: HttpClient = {
    async request(request, config) {
      observedRequests = [...observedRequests, request]
      return defaultHttpClient.request(request, config)
    },
  }
  const commonOptions = { apiKey: 'your-key', baseUrl: 'data:,#' }
  const client = new UniversesClient({
    ...commonOptions,
    httpClient: tracedHttpClient,
  })
  const undecoratedClient = new UniversesClient({
    ...commonOptions,
    httpClient: defaultHttpClient,
  })
  const parameters: DeleteExperienceIconParameters = {
    languageCode: 'en',
    universeId: '42',
  }
  expect(client).toBeInstanceOf(UniversesClient)
  return Promise.all([
    client.icon.delete(parameters),
    undecoratedClient.icon.delete(parameters),
  ]).then(([result, undecoratedResult]) => {
    expect(observedRequests).toStrictEqual([
      {
        method: 'DELETE',
        url: '/legacy-game-internationalization/v1/game-icon/games/42/language-codes/en',
      },
    ])
    expect(result).toStrictEqual({ data: undefined, success: true })
    expect(result).toStrictEqual(undecoratedResult)
  })
})
