// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  createFetchHttpClient,
  type HttpClient,
  type HttpRequest,
} from '@bedrock-rbx/ocale'
import { UniversesClient } from '@bedrock-rbx/ocale/universes'

it('Example 1', () => {
  const defaultHttpClient = createFetchHttpClient()
  const observedRequests = new Array<HttpRequest>()
  const tracedHttpClient: HttpClient = {
    async request(request, config) {
      observedRequests.push(request)
      return defaultHttpClient.request(request, config)
    },
  }
  const client = new UniversesClient({
    apiKey: 'your-key',
    httpClient: tracedHttpClient,
  })
  expect(client).toBeInstanceOf(UniversesClient)
})
