// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { AdmissionWait, AdmissionWaitObserver } from '@bedrock-rbx/ocale'

it('@since unreleased', () => {
  let heldSince: number | undefined
  let heldMs = 0
  const onAdmissionWait: AdmissionWaitObserver = (wait) => {
    heldSince = wait.phase === 'start' ? 0 : undefined
    heldMs += wait.phase === 'end' ? (wait.waitMs ?? 0) : 0
  }
  const queued: AdmissionWait = { phase: 'start', reason: 'operation-queue' }
  const sent: AdmissionWait = {
    phase: 'end',
    reason: 'operation-queue',
    waitMs: 100,
  }
  onAdmissionWait(queued)
  onAdmissionWait(sent)
  expect(heldSince).toBeUndefined()
  expect(heldMs).toBe(100)
})
