// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type {
  AdmissionWaitReason,
  AdmissionWaitEvent,
  AdmissionWaitObserver,
} from '@bedrock-rbx/ocale'

it('@since 0.3.1', () => {
  const reason: AdmissionWaitReason = 'retry-delay'
  expect(reason).toBe('retry-delay')
})

it('@since 0.3.1', () => {
  const event: AdmissionWaitEvent = {
    durationMs: 500,
    phase: 'started',
    reason: 'reported-budget',
  }
  expect(event.durationMs).toBe(500)
})

it('@since 0.3.1', () => {
  const events: AdmissionWaitEvent[] = []
  const observer: AdmissionWaitObserver = (event) => events.push(event)
  observer({ phase: 'started', reason: 'operation-queue' })
  expect(events).toHaveLength(1)
})
