// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { BadgesClient } from '@bedrock-rbx/ocale/badges'

it('Example 1', () => {
  const client = new BadgesClient({ apiKey: 'your-key' })
  expect(client).toBeInstanceOf(BadgesClient)
})
