// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { ApiError } from '@bedrock/ocale'

it('Example 1', () => {
  const error = new ApiError('Game pass not found', {
    code: 'NotFound',
    statusCode: 404,
  })
  expect(error).toBeInstanceOf(ApiError)
  expect(error.statusCode).toBe(404)
  expect(error.code).toBe('NotFound')
})
