// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { ApiError, requestContextOf } from '@bedrock-rbx/ocale'

it('Example 1', () => {
  const error = new ApiError('HTTP 404: Pass not found (code NotFound)', {
    code: 'NotFound',
    details: { errorCode: 'NotFound', message: 'Pass not found' },
    statusCode: 404,
  })
  expect(error).toBeInstanceOf(ApiError)
  expect(error.statusCode).toBe(404)
  expect(error.code).toBe('NotFound')
  expect(error.details).toEqual({
    errorCode: 'NotFound',
    message: 'Pass not found',
  })
})

it('Example 2', () => {
  const original = new ApiError('HTTP 404', {
    elapsedMs: 512,
    method: 'GET',
    statusCode: 404,
    url: 'https://apis.roblox.com/cloud/v2/universes/1',
  })
  const rewrapped = new ApiError('Universe 1 was not found; adoption failed', {
    ...requestContextOf(original),
    statusCode: 404,
  })
  expect(rewrapped.method).toBe('GET')
  expect(rewrapped.url).toBe('https://apis.roblox.com/cloud/v2/universes/1')
  expect(rewrapped.elapsedMs).toBe(512)
})
