// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { ApiError, OpenCloudError } from '@bedrock-rbx/ocale'

it('Example 1', () => {
  const err: OpenCloudError = new ApiError('HTTP 404: Queue items not found.', {
    code: 'NOT_FOUND',
    statusCode: 404,
  })
  expect(err.code).toBe('NOT_FOUND')
  expect(new OpenCloudError('no classifier').code).toBeUndefined()
})
