// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { PermissionError } from '@bedrock-rbx/ocale'

it('Example 1', () => {
  const error = new PermissionError('HTTP 403', {
    operationKey: 'developer-products.create',
    requiredScopes: ['creator-store-product:write'],
    statusCode: 403,
  })
  expect(error).toBeInstanceOf(PermissionError)
  expect(error.requiredScopes).toStrictEqual(['creator-store-product:write'])
  expect(error.operationKey).toBe('developer-products.create')
})
