// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { PollAbortedError } from '@bedrock-rbx/ocale'

it('Example 1', () => {
  const error = new PollAbortedError('polling was aborted', {
    reason: 'user cancelled',
  })
  expect(error).toBeInstanceOf(PollAbortedError)
  expect(error.reason).toBe('user cancelled')
})
