// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { PollTimeoutError } from '@bedrock-rbx/ocale'

it('Example 1', () => {
  const error = new PollTimeoutError('polling timed out after 5 s', {
    lastObservedTask: { state: 'PROCESSING' as const },
    timeoutMs: 5000,
  })
  expect(error).toBeInstanceOf(PollTimeoutError)
  expect(error.timeoutMs).toBe(5000)
  expect(error.lastObservedTask).toStrictEqual({ state: 'PROCESSING' })
})
