// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { RateLimitError } from '@bedrock/ocale'

it('Example 1', () => {
  const error = new RateLimitError('Too many requests', {
    retryAfterSeconds: 30,
  })
  expect(error).toBeInstanceOf(RateLimitError)
  expect(error.retryAfterSeconds).toBe(30)
})
