// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { RateLimitError, RateLimitWaitRefusedError } from '@bedrock-rbx/ocale'

it('Example 1', () => {
  const error = new RateLimitWaitRefusedError(
    'Rate limit asks for a 300s wait',
    {
      cause: new RateLimitError('Rate limited', {
        remaining: 0,
        retryAfterSeconds: 300,
      }),
    },
  )
  expect(error.retryAfterSeconds).toBe(300)
  expect(error.remaining).toBe(0)
})
