// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { RequestAbortedError } from '@bedrock-rbx/ocale'

it('Example 1', () => {
  const error = new RequestAbortedError('Request was aborted', {
    reason: 'superseded',
  })
  expect(error).toBeInstanceOf(RequestAbortedError)
  expect(error.reason).toBe('superseded')
})
