// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { RequestDeadlineExceededError } from '@bedrock-rbx/ocale'

it('Example 1', () => {
  const error = new RequestDeadlineExceededError('Request deadline elapsed', {
    deadlineMs: 1000000,
    remainingMs: 0,
    waitReason: 'operation-queue',
  })
  expect(error.remainingMs).toBe(0)
  expect(error.waitReason).toBe('operation-queue')
})
