// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { RetryDelayExceededError } from '@bedrock-rbx/ocale'

it('Example 1', () => {
  const error = new RetryDelayExceededError(
    'Retry delay exceeds the request deadline',
    {
      deadlineMs: 1000000,
      remainingMs: 495000,
      retryAfterMs: 1856000,
    },
  )
  expect(error.retryAfterMs).toBe(1856000)
  expect(error.remainingMs).toBe(495000)
})
