// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { ValidationError } from '@bedrock/ocale'

it('Example 1', () => {
  const error = new ValidationError('Place body is empty', {
    code: 'empty_body',
  })
  expect(error).toBeInstanceOf(ValidationError)
  expect(error.code).toBe('empty_body')
})
