// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { StorageClient } from '@bedrock/ocale/storage'

it('Example 1', () => {
  const client = new StorageClient({ apiKey: 'your-key' })
  expect(client).toBeInstanceOf(StorageClient)
})
