// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { Emitter } from '@bedrock-rbx/core'

it('Example 1', () => {
  const emit: Emitter = ({ environments }) => {
    const count = environments['production']?.resources.length ?? 0
    return [
      { content: `return { count = ${String(count)} }\n`, path: 'ids.luau' },
    ]
  }
  const files = emit({
    environments: {
      production: { environment: 'production', resources: [], version: 1 },
    },
  })
  expect(files).toStrictEqual([
    { content: 'return { count = 0 }\n', path: 'ids.luau' },
  ])
})
