// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  realValue,
  pushedValue,
  isRedacted,
  asResourceKey,
  asRobloxAssetId,
  asSha256Hex,
  codegenView,
  type ResourceCurrentState,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  expect(realValue('VIP Pass')).toBe('VIP Pass')
  expect(realValue({ redacted: 'Redacted Pass', value: 'VIP Pass' })).toBe(
    'VIP Pass',
  )
})

it('Example 2', () => {
  expect(pushedValue(500)).toBe(500)
  expect(pushedValue({ redacted: 99999, value: 500 })).toBe(99999)
})

it('Example 3', () => {
  expect(isRedacted('VIP Pass')).toBeFalse()
  expect(
    isRedacted({ redacted: 'Redacted Pass', value: 'VIP Pass' }),
  ).toBeTrue()
})

it('Example 4', () => {
  const pass: ResourceCurrentState<'gamePass'> = {
    description: '',
    icon: { 'en-us': 'assets/vip-icon.png' },
    iconFileHashes: {
      'en-us': asSha256Hex(
        'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      ),
    },
    key: asResourceKey('vip-pass'),
    kind: 'gamePass',
    name: 'Redacted Pass',
    outputs: {
      assetId: asRobloxAssetId('9876543210'),
      iconAssetIds: { 'en-us': asRobloxAssetId('1122334455') },
    },
    price: 99999,
  }
  const view = codegenView(pass, { name: 'VIP Pass', price: 500 })
  expect(realValue(view.name)).toBe('VIP Pass')
  expect(view.description).toBe('')
})
