// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type {
  ConfigValidationIssue,
  PluginLoadFailureReason,
  ConfigError,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const issue: ConfigValidationIssue = {
    message: 'must be a number',
    path: ['passes', 'vip-pass', 'price'],
  }
  expect(issue.path).toStrictEqual(['passes', 'vip-pass', 'price'])
})

it('Example 2', () => {
  function remedy(reason: PluginLoadFailureReason): string {
    switch (reason) {
      case 'importThrew': {
        return 'the plugin threw while loading; check its own configuration'
      }
      case 'invalidExport': {
        return 'the module is not a bedrock plugin'
      }
      case 'notInstalled': {
        return 'install the package, or correct the specifier'
      }
    }
  }
  expect(remedy('notInstalled')).toBe(
    'install the package, or correct the specifier',
  )
  expect(remedy('importThrew')).toBe(
    'the plugin threw while loading; check its own configuration',
  )
})

it('Example 3', () => {
  function describe(err: ConfigError): string {
    switch (err.kind) {
      case 'fileNotFound': {
        return `no bedrock config under ${err.searchedFrom}`
      }
      case 'parseFailed': {
        return `${err.sourceFile}: ${err.message}`
      }
      case 'configFunctionFailed': {
        return `${err.sourceFile}: config function threw: ${err.message}`
      }
      case 'validationFailed': {
        const first = err.issues[0]
        return first
          ? `${err.sourceFile}: ${first.path.join('.')} ${first.message}`
          : `${err.sourceFile}: invalid`
      }
      case 'luauRuntimeMissing': {
        return `${err.sourceFile}: ${err.hint}`
      }
      case 'pluginLoadFailed': {
        return `plugin '${err.specifier}' (${err.reason}): ${err.message}`
      }
    }
  }
  expect(describe({ kind: 'fileNotFound', searchedFrom: '/proj' })).toBe(
    'no bedrock config under /proj',
  )
  expect(
    describe({
      kind: 'parseFailed',
      sourceFile: 'bedrock.config.yaml',
      message: 'unexpected end of the stream',
    }),
  ).toBe('bedrock.config.yaml: unexpected end of the stream')
  expect(
    describe({
      kind: 'configFunctionFailed',
      sourceFile: 'bedrock.config.ts',
      message: 'boom',
    }),
  ).toBe('bedrock.config.ts: config function threw: boom')
  expect(
    describe({
      kind: 'validationFailed',
      sourceFile: 'bedrock.config.ts',
      issues: [
        { path: ['passes', 'vip', 'price'], message: 'must be a number' },
      ],
    }),
  ).toBe('bedrock.config.ts: passes.vip.price must be a number')
  expect(
    describe({
      kind: 'luauRuntimeMissing',
      sourceFile: 'bedrock.config.luau',
      hint: 'install lute via mise',
    }),
  ).toBe('bedrock.config.luau: install lute via mise')
  expect(
    describe({
      kind: 'pluginLoadFailed',
      specifier: '@bedrock-rbx/state-s3',
      reason: 'notInstalled',
      message: "Cannot find package '@bedrock-rbx/state-s3'",
    }),
  ).toBe(
    "plugin '@bedrock-rbx/state-s3' (notInstalled): Cannot find package '@bedrock-rbx/state-s3'",
  )
})
