import type { CodegenFile, EmitInput, Emitter } from "./codegen.ts";
import type { CodegenConfig } from "./schema.ts";
import type { BedrockState } from "./state.ts";

/**
 * Options for {@link createDefaultEmitter}.
 *
 * @since 0.1.0
 */
export interface DefaultEmitterOptions {
	/**
	 * Also write a `resources.d.ts` declaration beside the Luau module so
	 * roblox-ts consumers get type-safety over the same constants. Defaults to
	 * `false` (Luau module only).
	 */
	readonly typeDeclarations?: boolean | undefined;
}

/**
 * Default directory the generated files are written under, relative to the
 * working directory. Sits inside the managed `.bedrock/` directory but in its
 * own `generated/` subdirectory, so codegen output stays clear of the
 * `bedrock setup`-managed type files; consume it as `@bedrock/generated/resources`.
 *
 * @since 0.1.0
 */
export const DEFAULT_CODEGEN_OUTPUT_DIR = ".bedrock/generated";

/**
 * Resolve the directory the default node-fs writer roots codegen output at:
 * the configured `codegen.output` when set, otherwise
 * {@link DEFAULT_CODEGEN_OUTPUT_DIR}. Lets `deploy` write a working file with
 * no `output` configured (the zero-config path) while still honoring an
 * explicit override.
 *
 * @param codegen - The resolved `codegen` config section, or `undefined`.
 * @returns The output directory to write generated files under.
 */
export function resolveCodegenOutputDirectory(codegen: CodegenConfig | undefined): string {
	return codegen?.output ?? DEFAULT_CODEGEN_OUTPUT_DIR;
}

const LUAU_FILE = "resources.luau";
const DECLARATION_FILE = "resources.d.ts";
const LUAU_HEADER = "-- This file is generated by bedrock. Do not edit by hand.";
const DECLARATION_HEADER = "// This file is generated by bedrock. Do not edit by hand.";
const DECLARATION_CONST = "resources";

const TAB = "\t";
const LUAU_IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;
const TS_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

type IdTree = Record<string, Record<string, unknown>>;

/**
 * The default codegen {@link Emitter}: turns the per-environment deploy state
 * into a Luau module of Roblox-assigned IDs keyed by environment name, then
 * resource key, then that resource's outputs. Asset IDs are
 * emitted as Luau number literals so game code can pass them straight to
 * Roblox APIs. With `typeDeclarations`, a `resources.d.ts` companion is written
 * alongside so roblox-ts consumers type the same module.
 *
 * It is exported so a project can wrap it rather than replace it: call the
 * returned emitter, then append or post-process its files.
 *
 * @since 0.1.0
 *
 * @param options - Optional toggles; `typeDeclarations` adds the `.d.ts` companion.
 * @returns An {@link Emitter} suitable for `DeployOptions.emit`.
 * @since 0.1.0
 * @example
 *
 * ```ts
 * import { createDefaultEmitter, type EmitInput, type Emitter } from "@bedrock-rbx/core";
 *
 * const base = createDefaultEmitter();
 * const emit: Emitter = async (input: EmitInput) => [
 *     ...(await base(input)),
 *     { content: "return {}\n", path: "extra.luau" },
 * ];
 *
 * const input: EmitInput = {
 *     environments: { production: { environment: "production", resources: [], version: 1 } },
 * };
 * return Promise.resolve(emit(input)).then((files) => {
 *     expect(files.map((file) => file.path)).toStrictEqual(["resources.luau", "extra.luau"]);
 * });
 * ```
 */
export function createDefaultEmitter(options?: DefaultEmitterOptions): Emitter {
	const shouldWriteDeclarations = options?.typeDeclarations === true;
	return ({ environments }: EmitInput): ReadonlyArray<CodegenFile> => {
		const tree = buildTree(environments);
		const luauFile: CodegenFile = { content: renderLuau(tree), path: LUAU_FILE };
		return shouldWriteDeclarations
			? [luauFile, { content: renderDeclaration(tree), path: DECLARATION_FILE }]
			: [luauFile];
	};
}

function buildTree(environments: Readonly<Record<string, BedrockState>>): IdTree {
	return Object.fromEntries(
		Object.entries(environments).map(([environment, state]) => {
			return [
				environment,
				Object.fromEntries(
					state.resources.map((resource) => [resource.key, resource.outputs]),
				),
			];
		}),
	);
}

function renderLuau(tree: IdTree): string {
	return `${LUAU_HEADER}\n\nreturn ${renderLuauTable(tree, 0)}\n`;
}

function renderDeclaration(tree: IdTree): string {
	return `${DECLARATION_HEADER}\ndeclare const ${DECLARATION_CONST}: ${renderDeclarationType(tree, 0)};\nexport = ${DECLARATION_CONST};\n`;
}

function sortedDefinedKeys(record: Readonly<Record<string, unknown>>): Array<string> {
	return Object.keys(record)
		.filter((key) => record[key] !== undefined)
		.toSorted();
}

function luauKey(name: string): string {
	return LUAU_IDENTIFIER.test(name) ? name : `["${name}"]`;
}

function renderLuauTable(record: Readonly<Record<string, unknown>>, indent: number): string {
	const keys = sortedDefinedKeys(record);
	if (keys.length === 0) {
		return "{}";
	}

	const inner = keys
		.map((key) => {
			return `${TAB.repeat(indent + 1)}${luauKey(key)} = ${renderLuauValue(record[key], indent + 1)},`;
		})
		.join("\n");

	return `{\n${inner}\n${TAB.repeat(indent)}}`;
}

function renderLuauValue(value: unknown, indent: number): string {
	if (typeof value === "object") {
		return renderLuauTable(value as Readonly<Record<string, unknown>>, indent);
	}

	// Every scalar output is a Roblox asset ID (a numeric string) or a numeric
	// count, so both render to a bare Luau number literal.
	return String(value);
}

function renderDeclarationType(value: unknown, indent: number): string {
	if (typeof value === "object") {
		return renderDeclarationObject(value as Readonly<Record<string, unknown>>, indent);
	}

	return "number";
}

function declarationKey(name: string): string {
	return TS_IDENTIFIER.test(name) ? name : JSON.stringify(name);
}

function renderDeclarationObject(
	record: Readonly<Record<string, unknown>>,
	indent: number,
): string {
	const keys = sortedDefinedKeys(record);
	if (keys.length === 0) {
		return "{}";
	}

	const inner = keys
		.map((key) => {
			return `${TAB.repeat(indent + 1)}readonly ${declarationKey(key)}: ${renderDeclarationType(record[key], indent + 1)};`;
		})
		.join("\n");

	return `{\n${inner}\n${TAB.repeat(indent)}}`;
}
