// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  createDefaultEmitter,
  type EmitInput,
  type Emitter,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const base = createDefaultEmitter()
  const emit: Emitter = async (input: EmitInput) => [
    ...(await base(input)),
    { content: 'return {}\n', path: 'extra.luau' },
  ]
  const input: EmitInput = {
    environments: {
      production: { environment: 'production', resources: [], version: 1 },
    },
  }
  return Promise.resolve(emit(input)).then((files) => {
    expect(files.map((file) => file.path)).toStrictEqual([
      'resources.luau',
      'extra.luau',
    ])
  })
})
