import { developerProductCurrent, gamePassCurrent, placeCurrent } from "#tests/helpers/resources";
import { assert, describe, expect, it } from "vitest";

import { asResourceKey, asRobloxAssetId } from "../types/ids.ts";
import type { CodegenFile, EmitInput } from "./codegen.ts";
import {
	createDefaultEmitter,
	DEFAULT_CODEGEN_OUTPUT_DIR,
	type DefaultEmitterOptions,
	resolveCodegenOutputDirectory,
} from "./default-emitter.ts";
import type { ResourceCurrentState } from "./resources.ts";
import type { BedrockState } from "./state.ts";

function stateOf(
	environment: string,
	resources: ReadonlyArray<ResourceCurrentState>,
): BedrockState {
	return { environment, resources, version: 1 };
}

function inputOf(environments: Record<string, BedrockState>): EmitInput {
	return { environments };
}

async function emitFiles(
	input: EmitInput,
	options?: DefaultEmitterOptions,
): Promise<ReadonlyArray<CodegenFile>> {
	return createDefaultEmitter(options)(input);
}

async function luauContent(input: EmitInput): Promise<string> {
	const files = await emitFiles(input);
	const file = files.find((entry) => entry.path === "resources.luau");
	assert(file !== undefined);
	return file.content;
}

describe(createDefaultEmitter, () => {
	it("should write a Luau module of deployed IDs keyed by environment then key", async () => {
		expect.assertions(1);

		const content = await luauContent(
			inputOf({
				production: stateOf("production", [gamePassCurrent()]),
				staging: stateOf("staging", []),
			}),
		);

		expect(content).toBe(
			[
				"-- This file is generated by bedrock. Do not edit by hand.",
				"",
				"return {",
				"\tproduction = {",
				'\t\t["vip-pass"] = {',
				"\t\t\tassetId = 9876543210,",
				"\t\t\ticonAssetIds = {",
				'\t\t\t\t["en-us"] = 1122334455,',
				"\t\t\t},",
				"\t\t},",
				"\t},",
				"\tstaging = {},",
				"}",
				"",
			].join("\n"),
		);
	});

	it("should sort environments and keys deterministically regardless of input order", async () => {
		expect.assertions(2);

		const alphaPass: ResourceCurrentState<"gamePass"> = {
			...gamePassCurrent(),
			key: asResourceKey("alpha-pass"),
			outputs: {
				assetId: asRobloxAssetId("1111111111"),
				iconAssetIds: { "en-us": asRobloxAssetId("2222222222") },
			},
		};
		const content = await luauContent(
			inputOf({
				production: stateOf("production", [gamePassCurrent(), alphaPass]),
				staging: stateOf("staging", []),
			}),
		);

		expect(content.indexOf("production")).toBeLessThan(content.indexOf("staging"));
		expect(content.indexOf("alpha-pass")).toBeLessThan(content.indexOf("vip-pass"));
	});

	it("should surface a redacted resource's real minted asset ID", async () => {
		expect.assertions(1);

		// A redacted resource (ADR-024) persists placeholder display fields but
		// keeps its real minted IDs in `outputs`. The emitter reads only
		// `outputs`, so redaction hides content, never the emitted identity.
		const redacted = gamePassCurrent({ name: "Redacted Pass", description: "" });
		const content = await luauContent(
			inputOf({ production: stateOf("production", [redacted]) }),
		);

		expect(content).toContain("assetId = 9876543210,");
	});

	it("should emit outputs for every resource kind, including numeric and nested fields", async () => {
		expect.assertions(3);

		const content = await luauContent(
			inputOf({
				production: stateOf("production", [
					placeCurrent({ outputs: { versionNumber: 7 } }),
					developerProductCurrent({
						outputs: {
							iconImageAssetId: asRobloxAssetId("900"),
							productId: asRobloxAssetId("800"),
						},
					}),
				]),
			}),
		);

		expect(content).toContain("versionNumber = 7,");
		expect(content).toContain("productId = 800,");
		expect(content).toContain("iconImageAssetId = 900,");
	});

	it("should omit an output field whose value is undefined", async () => {
		expect.assertions(2);

		const content = await luauContent(
			inputOf({
				production: stateOf("production", [
					developerProductCurrent({
						outputs: { iconImageAssetId: undefined, productId: asRobloxAssetId("800") },
					}),
				]),
			}),
		);

		expect(content).toContain("productId = 800,");
		expect(content).not.toContain("iconImageAssetId");
	});

	it("should write only the Luau module when type declarations are not requested", async () => {
		expect.assertions(1);

		const files = await emitFiles(
			inputOf({ production: stateOf("production", [gamePassCurrent()]) }),
		);

		expect(files.map((file) => file.path)).toStrictEqual(["resources.luau"]);
	});

	it("should write a .d.ts companion beside the Luau module when type declarations are requested", async () => {
		expect.assertions(2);

		const files = await emitFiles(
			inputOf({
				production: stateOf("production", [gamePassCurrent()]),
				staging: stateOf("staging", []),
			}),
			{ typeDeclarations: true },
		);

		expect(files.map((file) => file.path)).toStrictEqual(["resources.luau", "resources.d.ts"]);
		expect(files.find((file) => file.path === "resources.d.ts")!.content).toBe(
			[
				"// This file is generated by bedrock. Do not edit by hand.",
				"declare const resources: {",
				"\treadonly production: {",
				'\t\treadonly "vip-pass": {',
				"\t\t\treadonly assetId: number;",
				"\t\t\treadonly iconAssetIds: {",
				'\t\t\t\treadonly "en-us": number;',
				"\t\t\t};",
				"\t\t};",
				"\t};",
				"\treadonly staging: {};",
				"};",
				"export = resources;",
				"",
			].join("\n"),
		);
	});

	it("should let a custom emitter wrap the default and append its own files", async () => {
		expect.assertions(2);

		const base = createDefaultEmitter();
		async function wrapped(input: EmitInput): Promise<ReadonlyArray<CodegenFile>> {
			return [...(await base(input)), { content: "return {}\n", path: "extra.luau" }];
		}

		const files = await wrapped(
			inputOf({ production: stateOf("production", [gamePassCurrent()]) }),
		);

		expect(files.map((file) => file.path)).toStrictEqual(["resources.luau", "extra.luau"]);
		expect(files[0]!.content).toContain("assetId = 9876543210");
	});

	it("should expose the default output directory under bedrock's managed dir", () => {
		expect.assertions(1);

		expect(DEFAULT_CODEGEN_OUTPUT_DIR).toBe(".bedrock/generated");
	});
});

describe(resolveCodegenOutputDirectory, () => {
	it("should use the configured output directory when one is set", () => {
		expect.assertions(1);

		expect(resolveCodegenOutputDirectory({ enabled: true, output: "src/generated" })).toBe(
			"src/generated",
		);
	});

	it("should fall back to the default directory when no output is configured", () => {
		expect.assertions(2);

		expect(resolveCodegenOutputDirectory({ enabled: true })).toBe(".bedrock/generated");
		expect(resolveCodegenOutputDirectory(undefined)).toBe(".bedrock/generated");
	});
});
