// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { derivePriceFields } from '@bedrock/core'

it('Example 1', () => {
  expect(derivePriceFields({ price: undefined })).toStrictEqual({
    isForSale: false,
  })
  expect(derivePriceFields({ price: 250 })).toStrictEqual({
    isForSale: true,
    price: 250,
  })
})
