// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  asRobloxAssetId,
  asSha256Hex,
  diff,
  type GamePassDesiredState,
  type ResourceCurrentState,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const hash = asSha256Hex(
    'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  )
  const unchanged: GamePassDesiredState = {
    description: 'Grants VIP perks.',
    icon: { 'en-us': 'assets/vip-icon.png' },
    iconFileHashes: { 'en-us': hash },
    key: asResourceKey('vip-pass'),
    kind: 'gamePass',
    name: 'VIP Pass',
    price: 500,
  }
  const drifted: GamePassDesiredState = {
    ...unchanged,
    key: asResourceKey('legend-pass'),
    name: 'Legend Pass (renamed)',
  }
  const fresh: GamePassDesiredState = {
    ...unchanged,
    key: asResourceKey('rookie-pass'),
    name: 'Rookie Pass',
  }
  const current: ReadonlyArray<ResourceCurrentState> = [
    {
      ...unchanged,
      outputs: {
        assetId: asRobloxAssetId('111'),
        iconAssetIds: { 'en-us': asRobloxAssetId('222') },
      },
    },
    {
      ...drifted,
      name: 'Legend Pass',
      outputs: {
        assetId: asRobloxAssetId('333'),
        iconAssetIds: { 'en-us': asRobloxAssetId('444') },
      },
    },
  ]
  const ops = diff([unchanged, drifted, fresh], current)
  expect(ops.map((op) => op.type)).toEqual(['noop', 'update', 'create'])
})
