// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { renderDisplayNamePrefix } from '@bedrock-rbx/core'

it('Example 1', () => {
  expect(renderDisplayNamePrefix('staging')).toBe('[STAGING] ')
  expect(renderDisplayNamePrefix('staging', '{Label}: ')).toBe('Staging: ')
  expect(renderDisplayNamePrefix('dev', '{LABEL}-{label}')).toBe('DEV-dev')
})
