// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { validateEnvironmentName } from '@bedrock-rbx/core'

it('Example 1', () => {
  const ok = validateEnvironmentName('production')
  expect(ok.success).toBeTrue()
  const bad = validateEnvironmentName('prod/staging')
  expect(bad.success).toBeFalse()
})
