// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  asRobloxAssetId,
  asSha256Hex,
  findResource,
  type ResourceCurrentState,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const resources: ReadonlyArray<ResourceCurrentState> = [
    {
      description: 'Grants VIP perks.',
      icon: { 'en-us': 'assets/vip-icon.png' },
      iconFileHashes: {
        'en-us': asSha256Hex(
          'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        ),
      },
      key: asResourceKey('vip-pass'),
      kind: 'gamePass',
      name: 'VIP Pass',
      outputs: {
        assetId: asRobloxAssetId('9876543210'),
        iconAssetIds: { 'en-us': asRobloxAssetId('1122334455') },
      },
      price: 500,
    },
  ]
  const pass = findResource(resources, { key: 'vip-pass', kind: 'gamePass' })
  expect(pass?.outputs.assetId).toBe('9876543210')
  expect(findResource(resources, { kind: 'place' })).toBeUndefined()
})
