// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  type GamePassDesiredInput,
  asRobloxAssetId,
  type PlaceDesiredInput,
  flattenConfig,
  type Config,
} from 'bedrock'

it('Example 1', () => {
  const input: GamePassDesiredInput = {
    description: 'Grants VIP perks.',
    iconFilePath: 'assets/vip-icon.png',
    key: asResourceKey('vip-pass'),
    kind: 'gamePass',
    name: 'VIP Pass',
    price: 500,
  }
  expect(input.kind).toBe('gamePass')
})

it('Example 2', () => {
  const input: PlaceDesiredInput = {
    filePath: 'places/start.rbxl',
    key: asResourceKey('start-place'),
    kind: 'place',
    placeId: asRobloxAssetId('4711'),
  }
  expect(input.kind).toBe('place')
})

it('Example 3', () => {
  const config: Config = {
    passes: {
      'vip-pass': {
        description: 'Grants VIP perks.',
        iconFilePath: 'assets/vip-icon.png',
        name: 'VIP Pass',
        price: 500,
      },
    },
  }
  const inputs = flattenConfig(config)
  expect(inputs).toHaveLength(1)
  expect(inputs[0]!.kind).toBe('gamePass')
  expect(inputs[0]!.key).toBe('vip-pass')
})
