// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  type GamePassDesiredInput,
  asRobloxAssetId,
  type PlaceDesiredInput,
  UNIVERSE_SINGLETON_KEY,
  type UniverseDesiredInput,
  type DeveloperProductDesiredInput,
  flattenConfig,
  selectEnvironment,
  type Config,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const input: GamePassDesiredInput = {
    description: 'Grants VIP perks.',
    icon: { 'en-us': 'assets/vip-icon.png' },
    key: asResourceKey('vip-pass'),
    kind: 'gamePass',
    name: 'VIP Pass',
    price: 500,
  }
  expect(input.kind).toBe('gamePass')
})

it('Example 2', () => {
  const input: PlaceDesiredInput = {
    description: undefined,
    displayName: 'Start Place',
    filePath: 'places/start.rbxl',
    key: asResourceKey('start-place'),
    kind: 'place',
    placeId: asRobloxAssetId('4711'),
    serverSize: 50,
  }
  expect(input.kind).toBe('place')
  expect(input.displayName).toBe('Start Place')
})

it('Example 3', () => {
  const input: UniverseDesiredInput = {
    consoleEnabled: undefined,
    desktopEnabled: true,
    displayName: undefined,
    key: UNIVERSE_SINGLETON_KEY,
    kind: 'universe',
    mobileEnabled: undefined,
    tabletEnabled: undefined,
    universeId: asRobloxAssetId('1234567890'),
    voiceChatEnabled: true,
    vrEnabled: undefined,
  }
  expect(input.kind).toBe('universe')
  expect(input.key).toBe('main')
  expect(input.desktopEnabled).toBeTrue()
})

it('Example 4', () => {
  const input: DeveloperProductDesiredInput = {
    description: 'Stocks the player up with 1,000 premium gems.',
    key: asResourceKey('gem-pack'),
    kind: 'developerProduct',
    name: 'Gem Pack',
  }
  expect(input.kind).toBe('developerProduct')
})

it('Example 5', () => {
  const config: Config = {
    environments: {
      production: { places: { 'start-place': { placeId: '4711' } } },
    },
    passes: {
      'vip-pass': {
        description: 'Grants VIP perks.',
        icon: { 'en-us': 'assets/vip-icon.png' },
        name: 'VIP Pass',
        price: 500,
      },
    },
    places: { 'start-place': { filePath: 'places/start.rbxl' } },
  }
  const resolved = selectEnvironment(config, 'production')
  expect(resolved.success).toBeTrue()
  if (resolved.success) {
    const inputs = flattenConfig(resolved.data)
    expect(inputs.map((input) => input.kind)).toEqual(['gamePass', 'place'])
    expect(inputs.map((input) => input.key)).toEqual([
      'vip-pass',
      'start-place',
    ])
  }
})
