// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { getEnvironment } from '@bedrock-rbx/core'

it('Example 1', () => {
  const result = getEnvironment(['--env', 'production'], () => undefined)
  expect(result.success).toBeTrue()
  if (result.success) {
    expect(result.data).toBe('production')
  }
})
