// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { asSha256Hex, shouldReuploadIcon } from '@bedrock/core'

it('Example 1', () => {
  const previous = asSha256Hex(
    'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  )
  const fresh = asSha256Hex(
    '2d711642b726b04401627ca9fbac32f5c8530fb1903cc4db02258717921a4881',
  )
  expect(shouldReuploadIcon({ 'en-us': previous }, { 'en-us': previous })).toBe(
    false,
  )
  expect(shouldReuploadIcon({ 'en-us': previous }, { 'en-us': fresh })).toBe(
    true,
  )
})
