// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  type BaseOperation,
  asSha256Hex,
  type CreateOperation,
  asRobloxAssetId,
  type UpdateOperation,
  type NoopOperation,
  type Operation,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const base: BaseOperation = { key: asResourceKey('vip-pass') }
  expect(base.key).toBe('vip-pass')
})

it('Example 2', () => {
  const op: CreateOperation = {
    desired: {
      description: 'Grants VIP perks.',
      icon: { 'en-us': 'assets/vip-icon.png' },
      iconFileHashes: {
        'en-us': asSha256Hex(
          'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        ),
      },
      key: asResourceKey('vip-pass'),
      kind: 'gamePass',
      name: 'VIP Pass',
      price: 500,
    },
    key: asResourceKey('vip-pass'),
    type: 'create',
  }
  expect(op.type).toBe('create')
  expect(op.desired.kind).toBe('gamePass')
})

it('Example 3', () => {
  const op: UpdateOperation = {
    current: {
      description: 'Grants VIP perks.',
      icon: { 'en-us': 'assets/vip-icon.png' },
      iconFileHashes: {
        'en-us': asSha256Hex(
          'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        ),
      },
      key: asResourceKey('vip-pass'),
      kind: 'gamePass',
      name: 'VIP Pass',
      outputs: {
        assetId: asRobloxAssetId('9876543210'),
        iconAssetIds: { 'en-us': asRobloxAssetId('1122334455') },
      },
      price: 500,
    },
    desired: {
      description: 'Grants VIP perks plus emote.',
      icon: { 'en-us': 'assets/vip-icon.png' },
      iconFileHashes: {
        'en-us': asSha256Hex(
          'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        ),
      },
      key: asResourceKey('vip-pass'),
      kind: 'gamePass',
      name: 'VIP Pass',
      price: 750,
    },
    changedFields: ['description', 'price'],
    key: asResourceKey('vip-pass'),
    type: 'update',
  }
  expect(op.type).toBe('update')
  expect(op.changedFields).toStrictEqual(['description', 'price'])
  if (op.desired.kind === 'gamePass') {
    expect(op.desired.price).toBe(750)
  }
  if (op.current.kind === 'gamePass') {
    expect(op.current.outputs.assetId).toBe('9876543210')
  }
})

it('Example 4', () => {
  const op: NoopOperation = {
    key: asResourceKey('vip-pass'),
    kind: 'gamePass',
    type: 'noop',
  }
  expect(op.type).toBe('noop')
  expect(op.kind).toBe('gamePass')
  expect(op.key).toBe('vip-pass')
})

it('Example 5', () => {
  function describeOp(op: Operation): string {
    switch (op.type) {
      case 'create': {
        return `create ${op.desired.kind} ${op.key}`
      }
      case 'update': {
        return `update ${op.desired.kind} ${op.key}`
      }
      case 'noop': {
        return `noop ${op.key}`
      }
    }
  }
  const op: Operation = {
    key: asResourceKey('vip-pass'),
    kind: 'gamePass',
    type: 'noop',
  }
  expect(describeOp(op)).toBe('noop vip-pass')
})
