// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { asResourceKey, planFollowUpPatch } from '@bedrock/core'

it('Example 1', () => {
  const desired = {
    description: 'Stocks the player up with 1,000 premium gems.',
    isRegionalPricingEnabled: undefined,
    key: asResourceKey('gem-pack'),
    kind: 'developerProduct' as const,
    name: 'Gem Pack',
    price: undefined,
    storePageEnabled: true,
  }
  expect(planFollowUpPatch(desired, { storePageEnabled: false })).toStrictEqual(
    {
      storePageEnabled: true,
    },
  )
  expect(planFollowUpPatch(desired, { storePageEnabled: true })).toBeUndefined()
})
