// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type {
  StateBackendMigrateSource,
  StateBackendDeclaration,
  BedrockPlugin,
} from '@bedrock-rbx/core'
import { type } from 'arktype'

it('Example 1', () => {
  const source: StateBackendMigrateSource = {
    prompts: [{ key: 'objectKey', label: 'Object key of the Mantle state?' }],
    readBytes: async ({ coordinates, getEnv }) => {
      const key = getEnv('AWS_ACCESS_KEY_ID')
      if (key === undefined) {
        return { err: { reason: 'no credentials' }, success: false }
      }
      return {
        data: new TextEncoder().encode(`fetched ${coordinates['objectKey']}`),
        success: true,
      }
    },
  }
  return source
    .readBytes({
      coordinates: { objectKey: 'state/mantle.yml' },
      getEnv: () => 'key',
    })
    .then((fetched) => {
      expect(fetched.success).toBeTrue()
      if (fetched.success) {
        expect(new TextDecoder().decode(fetched.data)).toBe(
          'fetched state/mantle.yml',
        )
      }
    })
})

it('Example 2', () => {
  const schema = type({ bucket: 'string > 0' })
  const s3: StateBackendDeclaration<typeof schema.infer> = {
    name: 's3',
    schema,
    createPort({ getEnv, stateConfig }) {
      const key = getEnv('AWS_ACCESS_KEY_ID')
      if (key === undefined) {
        return {
          err: {
            detail: { variable: 'AWS_ACCESS_KEY_ID' },
            reason: 'no credentials',
          },
          success: false,
        }
      }
      const objects = new Map<string, string>()
      const keyFor = (environment: string) =>
        `${stateConfig.bucket}/${environment}.json`
      return {
        data: {
          read: async () => ({ data: undefined, success: true }),
          write: async (state) => {
            objects.set(keyFor(state.environment), key)
            return { data: undefined, success: true }
          },
        },
        success: true,
      }
    },
  }
  const built = s3.createPort({
    getEnv: () => 'example-access-key',
    stateConfig: { bucket: 'my-bucket' },
  })
  expect(s3.name).toBe('s3')
  expect(built.success).toBeTrue()
})

it('Example 3', () => {
  const plugin: BedrockPlugin = {
    stateBackends: [
      {
        name: 's3',
        schema: type({ bucket: 'string > 0' }),
        createPort: () => ({
          err: { reason: 'not implemented' },
          success: false,
        }),
      },
    ],
  }
  expect(plugin.stateBackends).toHaveLength(1)
})
