// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { buildPluginRegistry } from '@bedrock-rbx/core'
import { type } from 'arktype'

it('Example 1', () => {
  const registry = buildPluginRegistry([
    {
      plugin: {
        stateBackends: [{ name: 's3', schema: type({ bucket: 'string > 0' }) }],
      },
      specifier: '@example/state-s3',
    },
  ])
  expect(registry.success).toBeTrue()
  if (registry.success) {
    expect(registry.data.stateBackends.has('s3')).toBeTrue()
  }
})
