// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { StateBackendDeclaration, BedrockPlugin } from '@bedrock-rbx/core'
import { type } from 'arktype'

it('Example 1', () => {
  const s3: StateBackendDeclaration = {
    name: 's3',
    schema: type({ bucket: 'string > 0', 'region?': 'string' }),
  }
  expect(s3.name).toBe('s3')
})

it('Example 2', () => {
  const plugin: BedrockPlugin = {
    stateBackends: [{ name: 's3', schema: type({ bucket: 'string > 0' }) }],
  }
  expect(plugin.stateBackends).toHaveLength(1)
})
