// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { asResourceKey, type RebuildHook } from '@bedrock-rbx/core'

it('Example 1', () => {
  const rebuild: RebuildHook = ({ state }) => {
    const passes = state.resources.filter(
      (resource) => resource.kind === 'gamePass',
    )
    return [
      {
        bytes: new TextEncoder().encode(
          `-- built against ${String(passes.length)} passes`,
        ),
        key: asResourceKey('start-place'),
      },
    ]
  }
  return Promise.resolve(
    rebuild({
      state: { environment: 'production', resources: [], version: 1 },
    }),
  ).then((built) => {
    expect(built).toHaveLength(1)
    expect(built[0]?.key).toBe('start-place')
  })
})
