// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  type RebuiltPlace,
  type RebuildHook,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const rebuilt: RebuiltPlace = {
    bytes: new TextEncoder().encode('-- rebuilt place'),
    key: asResourceKey('start-place'),
  }
  expect(rebuilt.key).toBe('start-place')
  expect(rebuilt.bytes).toBeInstanceOf(Uint8Array)
})

it('Example 2', () => {
  const rebuild: RebuildHook = ({ state }) => {
    const passes = state.resources.filter(
      (resource) => resource.kind === 'gamePass',
    )
    return [
      {
        bytes: new TextEncoder().encode(
          `-- built against ${String(passes.length)} passes`,
        ),
        key: asResourceKey('start-place'),
      },
    ]
  }
  return Promise.resolve(
    rebuild({
      state: { environment: 'production', resources: [], version: 1 },
    }),
  ).then((built) => {
    expect(built).toHaveLength(1)
    expect(built[0]?.key).toBe('start-place')
  })
})
