// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  asSha256Hex,
  type GamePassDesiredState,
  asRobloxAssetId,
  type ResourceOutputsByKind,
  type ResourceOutputs,
  type ResourceCurrentState,
} from 'bedrock'

it('Example 1', () => {
  const pass: GamePassDesiredState = {
    description: 'Grants VIP perks.',
    iconFileHash: asSha256Hex(
      'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    ),
    iconFilePath: 'assets/vip-icon.png',
    key: asResourceKey('vip-pass'),
    kind: 'gamePass',
    name: 'VIP Pass',
    price: undefined,
  }
  expect(pass.kind).toBe('gamePass')
  expect(pass.price).toBeUndefined()
})

it('Example 2', () => {
  const outputs: ResourceOutputsByKind['gamePass'] = {
    assetId: asRobloxAssetId('9876543210'),
    iconAssetId: asRobloxAssetId('1122334455'),
  }
  expect(outputs.assetId).toBe('9876543210')
})

it('Example 3', () => {
  const outputs: ResourceOutputs<'gamePass'> = {
    assetId: asRobloxAssetId('9876543210'),
    iconAssetId: asRobloxAssetId('1122334455'),
  }
  expect(outputs.iconAssetId).toBe('1122334455')
})

it('Example 4', () => {
  const current: ResourceCurrentState<'gamePass'> = {
    description: 'Grants VIP perks.',
    iconFileHash: asSha256Hex(
      'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    ),
    iconFilePath: 'assets/vip-icon.png',
    key: asResourceKey('vip-pass'),
    kind: 'gamePass',
    name: 'VIP Pass',
    outputs: {
      assetId: asRobloxAssetId('9876543210'),
      iconAssetId: asRobloxAssetId('1122334455'),
    },
    price: 500,
  }
  expect(current.outputs.assetId).toBe('9876543210')
  expect(current.kind).toBe('gamePass')
})
