// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  asSha256Hex,
  type GamePassDesiredState,
  asRobloxAssetId,
  type PlaceDesiredState,
  UNIVERSE_SINGLETON_KEY,
  type UniverseDesiredState,
  type DeveloperProductDesiredState,
  type ResourceOutputsByKind,
  type ResourceCurrentState,
} from '@bedrock/core'

it('Example 1', () => {
  const pass: GamePassDesiredState = {
    description: 'Grants VIP perks.',
    icon: { 'en-us': 'assets/vip-icon.png' },
    iconFileHashes: {
      'en-us': asSha256Hex(
        'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      ),
    },
    key: asResourceKey('vip-pass'),
    kind: 'gamePass',
    name: 'VIP Pass',
    price: undefined,
  }
  expect(pass.kind).toBe('gamePass')
  expect(pass.price).toBeUndefined()
})

it('Example 2', () => {
  const place: PlaceDesiredState = {
    description: undefined,
    displayName: 'Start Place',
    fileHash: asSha256Hex(
      'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    ),
    filePath: 'places/start.rbxl',
    key: asResourceKey('start-place'),
    kind: 'place',
    placeId: asRobloxAssetId('4711'),
    serverSize: 50,
  }
  expect(place.kind).toBe('place')
  expect(place.displayName).toBe('Start Place')
  expect(place.description).toBeUndefined()
  expect(place.serverSize).toBe(50)
})

it('Example 3', () => {
  const universe: UniverseDesiredState = {
    consoleEnabled: undefined,
    desktopEnabled: true,
    discordSocialLink: {
      title: 'Join our Discord',
      uri: 'https://discord.gg/example',
    },
    displayName: 'Fun Universe',
    key: UNIVERSE_SINGLETON_KEY,
    kind: 'universe',
    mobileEnabled: false,
    privateServerPriceRobux: undefined,
    tabletEnabled: undefined,
    twitterSocialLink: undefined,
    universeId: asRobloxAssetId('1234567890'),
    voiceChatEnabled: true,
    vrEnabled: undefined,
  }
  expect(universe.kind).toBe('universe')
  expect('privateServerPriceRobux' in universe).toBeTrue()
  expect(universe.discordSocialLink?.title).toBe('Join our Discord')
  expect(universe.twitterSocialLink).toBeUndefined()
})

it('Example 4', () => {
  const product: DeveloperProductDesiredState = {
    description: 'Stocks the player up with 1,000 premium gems.',
    isRegionalPricingEnabled: true,
    key: asResourceKey('gem-pack'),
    kind: 'developerProduct',
    name: 'Gem Pack',
    price: 100,
    storePageEnabled: true,
  }
  expect(product.kind).toBe('developerProduct')
  expect(product.price).toBe(100)
})

it('Example 5', () => {
  const outputs: ResourceOutputsByKind['gamePass'] = {
    assetId: asRobloxAssetId('9876543210'),
    iconAssetIds: { 'en-us': asRobloxAssetId('1122334455') },
  }
  expect(outputs.assetId).toBe('9876543210')
})

it('Example 6', () => {
  const current: ResourceCurrentState<'gamePass'> = {
    description: 'Grants VIP perks.',
    icon: { 'en-us': 'assets/vip-icon.png' },
    iconFileHashes: {
      'en-us': asSha256Hex(
        'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      ),
    },
    key: asResourceKey('vip-pass'),
    kind: 'gamePass',
    name: 'VIP Pass',
    outputs: {
      assetId: asRobloxAssetId('9876543210'),
      iconAssetIds: { 'en-us': asRobloxAssetId('1122334455') },
    },
    price: 500,
  }
  expect(current.outputs.assetId).toBe('9876543210')
  expect(current.kind).toBe('gamePass')
})

it('Example 7', () => {
  expect(UNIVERSE_SINGLETON_KEY).toBe('main')
})
