// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { resolveStateConfig } from '@bedrock-rbx/core'

it('Example 1', () => {
  const result = resolveStateConfig(
    {
      state: { backend: 'gist', gistId: 'root-gist' },
      environments: {
        production: { state: { backend: 'gist', gistId: 'prod-gist' } },
      },
    },
    'production',
  )
  expect(result.success).toBeTrue()
  if (result.success) {
    expect(result.data).toContainEntry(['gistId', 'prod-gist'])
  }
})
