// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  type ResourceEntryByKind,
  type Config,
  isGistStateConfig,
  type StateConfig,
  validateConfig,
} from '@bedrock/core'

it('Example 1', () => {
  const entry: ResourceEntryByKind['gamePass'] = {
    description: 'Grants VIP perks.',
    iconFilePath: 'assets/vip-icon.png',
    name: 'VIP Pass',
    price: 500,
  }
  expect(entry.name).toBe('VIP Pass')
})

it('Example 2', () => {
  const config: Config = {
    state: { backend: 'gist', gistId: 'abc123def456' },
    passes: {
      'vip-pass': {
        description: 'Grants VIP perks.',
        iconFilePath: 'assets/vip-icon.png',
        name: 'VIP Pass',
        price: 500,
      },
    },
  }
  expect(config.passes!['vip-pass']!.name).toBe('VIP Pass')
})

it('Example 3', () => {
  const config: StateConfig = { backend: 'gist', gistId: 'abc' }
  expect(isGistStateConfig(config)).toBeTrue()
  if (isGistStateConfig(config)) {
    expect(config.gistId).toBe('abc')
  }
})

it('Example 4', () => {
  const ok = validateConfig(
    {
      passes: {
        'vip-pass': {
          description: 'VIP perks.',
          iconFilePath: 'assets/vip.png',
          name: 'VIP Pass',
          price: 500,
        },
      },
    },
    'bedrock.config.ts',
  )
  expect(ok.success).toBeTrue()
  const err = validateConfig(
    { passes: { 'vip-pass': { name: 'VIP' } } },
    'bedrock.config.ts',
  )
  expect(err.success).toBeFalse()
  if (!err.success) {
    expect(err.err.kind).toBe('validationFailed')
  }
})
