// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type {
  GamePassEntry,
  RedactedGamePassOverride,
  PlaceEntry,
  RedactedPlaceOverride,
  Config,
  RedactedEnvironmentOverride,
  DeveloperProductEntry,
  RedactedDeveloperProductOverride,
  ResourceEntryByKind,
  StateConfig,
} from '@bedrock-rbx/core/config'
import {
  selectEnvironment,
  type ResolvedConfig,
  isGistStateConfig,
  validateConfig,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const override: RedactedGamePassOverride = { name: 'Closed Beta', price: 500 }
  const entry: GamePassEntry = {
    name: 'VIP Pass',
    description: 'Grants VIP perks.',
    icon: { 'en-us': 'assets/vip.png' },
    price: 1500,
    redacted: override,
  }
  expect(entry.redacted).toStrictEqual({ name: 'Closed Beta', price: 500 })
})

it('Example 2', () => {
  const override: RedactedPlaceOverride = { displayName: 'Hidden Project' }
  const entry: PlaceEntry = {
    description: 'The lobby place.',
    displayName: 'Start Place',
    filePath: 'places/start.rbxl',
    redacted: override,
  }
  expect(entry.redacted).toStrictEqual({ displayName: 'Hidden Project' })
})

it('Example 3', () => {
  const devRedaction: RedactedEnvironmentOverride = { price: 1 }
  const config: Config = {
    environments: { dev: { redacted: devRedaction } },
    passes: {
      'vip-pass': {
        name: 'VIP Pass',
        description: 'Grants VIP perks.',
        icon: { 'en-us': 'assets/vip.png' },
        price: 500,
      },
    },
    state: { backend: 'gist', gistId: 'abc123' },
  }
  expect(config.environments['dev']?.redacted).toStrictEqual({ price: 1 })
})

it('Example 4', () => {
  const override: RedactedDeveloperProductOverride = {
    name: 'Closed Beta Pack',
    price: 500,
  }
  const entry: DeveloperProductEntry = {
    name: 'Gem Pack',
    description: 'Stocks the player up with 1,000 premium gems.',
    price: 1500,
    redacted: override,
  }
  expect(entry.redacted).toStrictEqual({ name: 'Closed Beta Pack', price: 500 })
})

it('Example 5', () => {
  const entry: ResourceEntryByKind['gamePass'] = {
    description: 'Grants VIP perks.',
    icon: { 'en-us': 'assets/vip-icon.png' },
    name: 'VIP Pass',
    price: 500,
  }
  expect(entry.name).toBe('VIP Pass')
})

it('Example 6', () => {
  const config: Config = {
    environments: { production: {} },
    state: { backend: 'gist', gistId: 'abc123def456' },
    passes: {
      'vip-pass': {
        description: 'Grants VIP perks.',
        icon: { 'en-us': 'assets/vip-icon.png' },
        name: 'VIP Pass',
        price: 500,
      },
    },
  }
  expect(config.passes!['vip-pass']!.name).toBe('VIP Pass')
})

it('Example 7', () => {
  const config: Config = {
    environments: {
      production: { places: { 'start-place': { placeId: '4711' } } },
    },
    places: { 'start-place': { filePath: 'places/start.rbxl' } },
    state: { backend: 'gist', gistId: 'abc' },
  }
  const result = selectEnvironment(config, 'production')
  expect(result.success).toBeTrue()
  if (result.success) {
    const resolved: ResolvedConfig = result.data
    expect(resolved.places?.['start-place']?.placeId).toBe('4711')
  }
})

it('Example 8', () => {
  const config: StateConfig = { backend: 'gist', gistId: 'abc' }
  expect(isGistStateConfig(config)).toBeTrue()
  if (isGistStateConfig(config)) {
    expect(config.gistId).toBe('abc')
  }
})

it('Example 9', () => {
  const ok = validateConfig(
    {
      environments: { production: {} },
      passes: {
        'vip-pass': {
          description: 'VIP perks.',
          icon: { 'en-us': 'assets/vip.png' },
          name: 'VIP Pass',
          price: 500,
        },
      },
    },
    'bedrock.config.ts',
  )
  expect(ok.success).toBeTrue()
  const err = validateConfig(
    {
      environments: { production: {} },
      passes: { 'vip-pass': { name: 'VIP' } },
    },
    'bedrock.config.ts',
  )
  expect(err.success).toBeFalse()
  if (!err.success) {
    expect(err.err.kind).toBe('validationFailed')
  }
})
