// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type {
  ResourceEntryByKind,
  Config,
  StateConfig,
} from '@bedrock-rbx/core/config'
import {
  selectEnvironment,
  type ResolvedConfig,
  isGistStateConfig,
  validateConfig,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const entry: ResourceEntryByKind['gamePass'] = {
    description: 'Grants VIP perks.',
    icon: { 'en-us': 'assets/vip-icon.png' },
    name: 'VIP Pass',
    price: 500,
  }
  expect(entry.name).toBe('VIP Pass')
})

it('Example 2', () => {
  const config: Config = {
    environments: { production: {} },
    state: { backend: 'gist', gistId: 'abc123def456' },
    passes: {
      'vip-pass': {
        description: 'Grants VIP perks.',
        icon: { 'en-us': 'assets/vip-icon.png' },
        name: 'VIP Pass',
        price: 500,
      },
    },
  }
  expect(config.passes!['vip-pass']!.name).toBe('VIP Pass')
})

it('Example 3', () => {
  const config: Config = {
    environments: {
      production: { places: { 'start-place': { placeId: '4711' } } },
    },
    places: { 'start-place': { filePath: 'places/start.rbxl' } },
    state: { backend: 'gist', gistId: 'abc' },
  }
  const result = selectEnvironment(config, 'production')
  expect(result.success).toBeTrue()
  if (result.success) {
    const resolved: ResolvedConfig = result.data
    expect(resolved.places?.['start-place']?.placeId).toBe('4711')
  }
})

it('Example 4', () => {
  const config: StateConfig = { backend: 'gist', gistId: 'abc' }
  expect(isGistStateConfig(config)).toBeTrue()
  if (isGistStateConfig(config)) {
    expect(config.gistId).toBe('abc')
  }
})

it('Example 5', () => {
  const ok = validateConfig(
    {
      environments: { production: {} },
      passes: {
        'vip-pass': {
          description: 'VIP perks.',
          icon: { 'en-us': 'assets/vip.png' },
          name: 'VIP Pass',
          price: 500,
        },
      },
    },
    'bedrock.config.ts',
  )
  expect(ok.success).toBeTrue()
  const err = validateConfig(
    {
      environments: { production: {} },
      passes: { 'vip-pass': { name: 'VIP' } },
    },
    'bedrock.config.ts',
  )
  expect(err.success).toBeFalse()
  if (!err.success) {
    expect(err.err.kind).toBe('validationFailed')
  }
})
