// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { selectEnvironment, type Config } from '@bedrock/core'

it('Example 1', () => {
  const config: Config = {
    environments: {
      production: { universe: { universeId: '999' } },
    },
    state: { backend: 'gist', gistId: 'abc123' },
    universe: { universeId: '111' },
  }
  const effective = selectEnvironment(config, 'production')
  expect(effective.success).toBeTrue()
  if (effective.success) {
    expect(effective.data.universe?.universeId).toBe('999')
    expect(effective.data.state.backend).toBe('gist')
  }
})
