// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { selectEnvironment } from '@bedrock-rbx/core'
import type { Config } from '@bedrock-rbx/core/config'

it('Example 1', () => {
  const config: Config = {
    environments: {
      production: { universe: { universeId: '999' } },
    },
    state: { backend: 'gist', gistId: 'abc123' },
    universe: { voiceChatEnabled: true },
  }
  const result = selectEnvironment(config, 'production')
  expect(result.success).toBeTrue()
  if (result.success) {
    expect(result.data.universe?.universeId).toBe('999')
    expect(result.data.universe?.voiceChatEnabled).toBeTrue()
    expect(result.data.state?.backend).toBe('gist')
  }
})
