// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { stateLockingCapabilityOf } from '@bedrock-rbx/core'

it('Example 1', () => {
  const capability = stateLockingCapabilityOf({
    stateConfig: { backend: 'gist', gistId: 'abc123' },
  })
  expect(capability).toBe('none')
})
