// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  serializeStateFile,
  type BedrockState,
  parseStateContents,
  parseStateFile,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const state: BedrockState = {
    environment: 'production',
    resources: [],
    version: 1,
  }
  const wire = serializeStateFile(state)
  expect(JSON.parse(wire)).toStrictEqual({
    $bedrock: { version: 1 },
    environment: 'production',
    resources: [],
  })
})

it('Example 2', () => {
  const parsed = parseStateContents(
    JSON.stringify({
      $bedrock: { version: 1 },
      environment: 'production',
      resources: [],
    }),
    's3://my-bucket/production.json',
  )
  expect(parsed.success).toBeTrue()
  if (parsed.success) {
    expect(parsed.data.environment).toBe('production')
  }
})

it('Example 3', () => {
  const freshStart = parseStateFile(
    undefined,
    'gist:abc123/state.production.json',
  )
  expect(freshStart.success).toBeTrue()
  if (freshStart.success) {
    expect(freshStart.data).toBeUndefined()
  }
})
