// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  asRobloxAssetId,
  asSha256Hex,
  type BedrockState,
  type StateError,
} from 'bedrock'

it('Example 1', () => {
  const state: BedrockState = {
    environment: 'production',
    resources: [
      {
        description: 'Grants VIP perks.',
        iconFileHash: asSha256Hex(
          'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        ),
        iconFilePath: 'assets/vip-icon.png',
        key: asResourceKey('vip-pass'),
        kind: 'gamePass',
        name: 'VIP Pass',
        outputs: {
          assetId: asRobloxAssetId('9876543210'),
          iconAssetId: asRobloxAssetId('1122334455'),
        },
        price: 500,
      },
    ],
    version: 1,
  }
  expect(state.version).toBe(1)
  expect(state.resources).toHaveLength(1)
})

it('Example 2', () => {
  const err: StateError = {
    file: '.bedrock/state/production.json',
    kind: 'stateError',
    reason: 'Corrupt JSON: unexpected token at line 1 column 5',
  }
  expect(err.kind).toBe('stateError')
})
