// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { serializeStateFile, type BedrockState } from '@bedrock/core'

it('Example 1', () => {
  const state: BedrockState = {
    environment: 'production',
    resources: [],
    version: 1,
  }
  const wire = serializeStateFile(state)
  expect(JSON.parse(wire)).toStrictEqual({
    $bedrock: { version: 1 },
    environment: 'production',
    resources: [],
  })
})
