// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  asRobloxAssetId,
  asSha256Hex,
  type BedrockState,
  type StateError,
} from '@bedrock/core'

it('Example 1', () => {
  const state: BedrockState = {
    environment: 'production',
    resources: [
      {
        description: 'Grants VIP perks.',
        icon: { 'en-us': 'assets/vip-icon.png' },
        iconFileHashes: {
          'en-us': asSha256Hex(
            'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
          ),
        },
        key: asResourceKey('vip-pass'),
        kind: 'gamePass',
        name: 'VIP Pass',
        outputs: {
          assetId: asRobloxAssetId('9876543210'),
          iconAssetIds: { 'en-us': asRobloxAssetId('1122334455') },
        },
        price: 500,
      },
    ],
    version: 1,
  }
  expect(state.version).toBe(1)
  expect(state.resources).toHaveLength(1)
})

it('Example 2', () => {
  const err: StateError = {
    file: '.bedrock/state/production.json',
    kind: 'stateError',
    reason: 'Corrupt JSON: unexpected token at line 1 column 5',
  }
  expect(err.kind).toBe('stateError')
})
