// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  asRobloxAssetId,
  asSha256Hex,
  validatePlan,
} from '@bedrock-rbx/core'

it('Example 1', () => {
  const result = validatePlan(
    [
      {
        description: 'Stocks the player up with 1,000 premium gems.',
        isRegionalPricingEnabled: undefined,
        key: asResourceKey('gem-pack'),
        kind: 'developerProduct',
        name: 'Gem Pack',
        price: undefined,
        storePageEnabled: undefined,
      },
    ],
    [
      {
        description: 'Stocks the player up with 1,000 premium gems.',
        icon: { 'en-us': 'assets/gem-pack.png' },
        iconFileHashes: {
          'en-us': asSha256Hex(
            'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
          ),
        },
        isRegionalPricingEnabled: undefined,
        key: asResourceKey('gem-pack'),
        kind: 'developerProduct',
        name: 'Gem Pack',
        outputs: { productId: asRobloxAssetId('9876543210') },
        price: undefined,
        storePageEnabled: undefined,
      },
    ],
  )
  expect(result.success).toBeFalse()
  if (!result.success) {
    expect(result.err.kind).toBe('iconRemovalRejected')
  }
})
