// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { asResourceKey } from 'bedrock'

it('Example 1', () => {
  const key = asResourceKey('vip-pass')
  expect(key).toBe('vip-pass')
  expect(() => asResourceKey('vip pass')).toThrow(RangeError)
})
