// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  isResourceKey,
  asResourceKey,
  isRobloxAssetId,
  asRobloxAssetId,
  isSha256Hex,
  asSha256Hex,
} from 'bedrock'

it('Example 1', () => {
  const valid = isResourceKey('vip-pass')
  const invalid = isResourceKey('vip pass')
  expect(valid).toBe(true)
  expect(invalid).toBe(false)
})

it('Example 2', () => {
  const key = asResourceKey('vip-pass')
  let thrown: unknown
  try {
    asResourceKey('vip pass')
  } catch (error) {
    thrown = error
  }
  expect(key).toBe('vip-pass')
  expect(thrown).toBeInstanceOf(RangeError)
})

it('Example 3', () => {
  const valid = isRobloxAssetId('12345')
  const invalid = isRobloxAssetId('12345abc')
  expect(valid).toBe(true)
  expect(invalid).toBe(false)
})

it('Example 4', () => {
  const id = asRobloxAssetId('12345')
  let thrown: unknown
  try {
    asRobloxAssetId('12345abc')
  } catch (error) {
    thrown = error
  }
  expect(id).toBe('12345')
  expect(thrown).toBeInstanceOf(RangeError)
})

it('Example 5', () => {
  const digest =
    'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
  const valid = isSha256Hex(digest)
  const invalid = isSha256Hex(digest.toUpperCase())
  expect(valid).toBe(true)
  expect(invalid).toBe(false)
})

it('Example 6', () => {
  const digest = asSha256Hex(
    'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  )
  let thrown: unknown
  try {
    asSha256Hex('deadbeef')
  } catch (error) {
    thrown = error
  }
  expect(digest).toHaveLength(64)
  expect(thrown).toBeInstanceOf(RangeError)
})
