const UPSTREAM_URL = "https://locale.roblox.com/v1/locales/supported-locales-for-creators";
const README_PATH = "vendor/README.md";
const VENDOR_JSON_PATH = "vendor/roblox-creator-locales.json";
const GENERATED_TS_PATH = "src/locales/data.generated.ts";
const PINNED_DATE_PATTERN = /^\*\*Pinned date:\*\* `\d{4}-\d{2}-\d{2}`$/m;

interface UpstreamLanguage {
	readonly name: string;
	readonly isRightToLeft: boolean;
	readonly languageCode: string;
	readonly nativeName: string;
}

interface UpstreamLocale {
	readonly name: string;
	readonly language: UpstreamLanguage;
	readonly locale: string;
	readonly nativeName: string;
}

interface UpstreamEntry {
	readonly isEnabledForFullExperience: boolean;
	readonly isEnabledForInGameUgc: boolean;
	readonly isEnabledForSignupAndLogin: boolean;
	readonly locale: UpstreamLocale;
}

interface UpstreamPayload {
	readonly data: ReadonlyArray<UpstreamEntry>;
}

interface VendoredEntry {
	readonly name: string;
	readonly isEnabledForFullExperience: boolean;
	readonly isEnabledForInGameUgc: boolean;
	readonly isEnabledForSignupAndLogin: boolean;
	readonly isRightToLeft: boolean;
	readonly languageCode: string;
	readonly locale: string;
	readonly nativeName: string;
}

function isUpstreamPayload(value: unknown): value is UpstreamPayload {
	if (typeof value !== "object" || value === null || !("data" in value)) {
		return false;
	}

	return Array.isArray(value.data);
}

async function fetchUpstream(): Promise<UpstreamPayload> {
	const response = await fetch(UPSTREAM_URL);
	if (!response.ok) {
		throw new Error(`failed to fetch creator locales: ${String(response.status)}`);
	}

	const raw = JSON.parse(await response.text());
	if (!isUpstreamPayload(raw)) {
		throw new Error("upstream creator-locales payload missing data array");
	}

	return raw;
}

function projectEntry(entry: UpstreamEntry): VendoredEntry {
	const {
		isEnabledForFullExperience,
		isEnabledForInGameUgc,
		isEnabledForSignupAndLogin,
		locale,
	} = entry;
	return {
		name: locale.name,
		isEnabledForFullExperience,
		isEnabledForInGameUgc,
		isEnabledForSignupAndLogin,
		isRightToLeft: locale.language.isRightToLeft,
		languageCode: locale.language.languageCode,
		locale: locale.locale,
		nativeName: locale.nativeName,
	};
}

function renderEntry(entry: VendoredEntry): string {
	const lines = [
		"\t{",
		`\t\tlocale: ${JSON.stringify(entry.locale)},`,
		`\t\tlanguageCode: ${JSON.stringify(entry.languageCode)},`,
		`\t\tname: ${JSON.stringify(entry.name)},`,
		`\t\tnativeName: ${JSON.stringify(entry.nativeName)},`,
		`\t\tisRightToLeft: ${String(entry.isRightToLeft)},`,
		`\t\tisEnabledForFullExperience: ${String(entry.isEnabledForFullExperience)},`,
		`\t\tisEnabledForInGameUgc: ${String(entry.isEnabledForInGameUgc)},`,
		`\t\tisEnabledForSignupAndLogin: ${String(entry.isEnabledForSignupAndLogin)},`,
		"\t},",
	];
	return lines.join("\n");
}

const HEADER = `// @generated by scripts/fetch-locales.ts. Do not edit by hand.
// Source: ${UPSTREAM_URL}

/**
 * One row in the vendored Roblox creator-locale list.
 *
 * @since 0.1.0
 */
export interface RobloxCreatorLocale {
\treadonly locale: string;
\treadonly languageCode: string;
\treadonly name: string;
\treadonly nativeName: string;
\treadonly isRightToLeft: boolean;
\treadonly isEnabledForFullExperience: boolean;
\treadonly isEnabledForInGameUgc: boolean;
\treadonly isEnabledForSignupAndLogin: boolean;
}
`;

const FOOTER = `] as const satisfies ReadonlyArray<RobloxCreatorLocale>;

/**
 * Roblox locale wire form (e.g. \`en_us\`, \`pt_br\`, \`ar_001\`). Used by
 * the legacy game-internationalization endpoints when
 * \`languageCodeType\` is \`Locale\`.
 *
 * @since 0.1.0
 */
export type RobloxLocale = (typeof ROBLOX_CREATOR_LOCALES)[number]["locale"];

/**
 * Roblox language wire form (e.g. \`en\`, \`fil\`, \`zh-hans\`). Used by
 * the legacy game-internationalization endpoints when
 * \`languageCodeType\` is \`Language\`.
 *
 * @since 0.1.0
 */
export type RobloxLanguageCode = (typeof ROBLOX_CREATOR_LOCALES)[number]["languageCode"];
`;

function renderModule(entries: ReadonlyArray<VendoredEntry>): string {
	const body = entries.map(renderEntry).join("\n");
	return `${HEADER}
/**
 * Vendored snapshot of
 * \`${UPSTREAM_URL}\`.
 * Refreshed by \`pnpm --filter @bedrock-rbx/ocale refresh-locales\`.
 *
 * @since 0.1.0
 */
export const ROBLOX_CREATOR_LOCALES = [
${body}
${FOOTER}`;
}

async function refreshPinnedDate(): Promise<void> {
	const today = new Date().toISOString().slice(0, 10);
	const readme = await Bun.file(README_PATH).text();
	if (!PINNED_DATE_PATTERN.test(readme)) {
		throw new Error(`failed to locate creator-locales pinned-date line in ${README_PATH}`);
	}

	const updated = readme.replace(PINNED_DATE_PATTERN, `**Pinned date:** \`${today}\``);
	await Bun.write(README_PATH, updated);
}

function byLocaleAsc(a: { locale: { locale: string } }, b: { locale: { locale: string } }): number {
	return a.locale.locale.localeCompare(b.locale.locale);
}

const upstream = await fetchUpstream();
const sorted: UpstreamPayload = { data: [...upstream.data].sort(byLocaleAsc) };
const entries = sorted.data.map(projectEntry);
await Bun.write(VENDOR_JSON_PATH, `${JSON.stringify(sorted, undefined, "\t")}\n`);
await Bun.write(GENERATED_TS_PATH, renderModule(entries));
await refreshPinnedDate();
