// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { add, multiply } from './example'

it('Example 1', () => {
  const result = add(2, 3)
  expect(result).toBe(5)
})

it('Example 2', () => {
  const result = add(-1, 1)
  expect(result).toBe(0)
})

it('Example 3', () => {
  const result = multiply(2, 3)
  expect(result).toBe(6)
})

it('Example 4', () => {
  const result = multiply(0, 5)
  expect(result).toBe(0)
})
