# yaml-language-server:
# $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

version: "0.2"
language: en

words:
  - arktype
  - bedrockrc
  - checkpointed
  - codegen
  - defu
  - ehostdown
  - extraheader
  - gameinternationalization
  - gitdir
  - gsub
  - guilded
  - includeif
  - luau
  - luaurc
  - lute
  - monocart
  - nonwords
  - ocale
  - pcall
  - pgrep
  - pulumi
  - rbxl
  - rbxlx
  - rbxts
  - rbxtsc
  - redactable
  - redactions
  - regenerable
  - retryable
  - rojo
  - shiki
  - stroustrup
  - unparseable
  - vitesse
  - worktree
  - worktrees
  - worktrunk
