# yaml-language-server:
# $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

version: "0.2"
language: en
words:
  - arktype
  - bedrockrc
  - codegen
  - defu
  - ehostdown
  - gameinternationalization
  - guilded
  - luau
  - luaurc
  - lute
  - monocart
  - nonwords
  - ocale
  - pgrep
  - pulumi
  - rbxl
  - rbxlx
  - redactable
  - redactions
  - regenerable
  - retryable
  - shiki
  - stroustrup
  - vitesse
  - worktree
  - worktrees
  - worktrunk
