# yaml-language-server:
# $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json

version: "0.2"
language: en
words:
  - arktype
  - bedrockrc
  - defu
  - gameinternationalization
  - guilded
  - luau
  - luaurc
  - lute
  - monocart
  - retryable
  - ocale
  - Pulumi
  - rbxl
  - rbxlx
  - worktree
  - worktrees
  - worktrunk
