// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { ExperienceThumbnailsClient } from '@bedrock/ocale/experience-thumbnails'

it('Example 1', () => {
  const client = new ExperienceThumbnailsClient({ apiKey: 'your-key' })
  expect(client).toBeInstanceOf(ExperienceThumbnailsClient)
})
