// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { PlacesClient } from '@bedrock/ocale/places'

it('Example 1', () => {
  const client = new PlacesClient({ apiKey: 'your-key' })
  expect(client).toBeInstanceOf(PlacesClient)
})
