// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { PublishParameters, PlaceVersion } from '@bedrock/ocale/places'

it('Example 1', () => {
  const params: PublishParameters = {
    body: new Uint8Array([60, 114, 111, 98, 108, 111, 120, 32]),
    format: 'rbxlx',
    placeId: '456',
    universeId: '123',
  }
  expect(params.format).toBe('rbxlx')
})

it('Example 2', () => {
  const version: PlaceVersion = { versionNumber: 42 }
  expect(version.versionNumber).toBeGreaterThan(0)
})
