// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { ExperiencesClient } from '@bedrock/ocale/experiences'

it('Example 1', () => {
  const client = new ExperiencesClient({ apiKey: 'your-key' })
  expect(client).toBeInstanceOf(ExperiencesClient)
})
