name: Lint PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: Lint PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        name: Lint PR title
        run: echo "$PR_TITLE" | pnpm commitlint --verbose
    timeout-minutes: 5
