// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { GamePassesClient } from '@bedrock/ocale/game-passes'
import { asRobloxAssetId, createGamePassDriver } from 'bedrock'

it('Example 1', () => {
  const client = new GamePassesClient({ apiKey: 'rbx-your-key' })
  const driver = createGamePassDriver({
    client,
    readFile: async () => new Uint8Array(),
    universeId: asRobloxAssetId('1234567890'),
  })
  expect(driver.create).toBeFunction()
})
