// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { ProgressEvent, ProgressPort } from '@bedrock-rbx/core'

it('Example 1', () => {
  const received: Array<ProgressEvent> = []
  const port: ProgressPort = {
    emit(event) {
      received.push(event)
    },
  }
  port.emit({
    environment: 'production',
    kind: 'deploySuccess',
    resourceCount: 3,
  })
  expect(received).toEqual([
    { environment: 'production', kind: 'deploySuccess', resourceCount: 3 },
  ])
})
