// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  asResourceKey,
  asRobloxAssetId,
  asSha256Hex,
  type ResourceDriver,
  OpenCloudError,
  type DriverRegistry,
} from '@bedrock/core'

it('Example 1', () => {
  const gamePassDriver: ResourceDriver<'gamePass'> = {
    async create(desired) {
      return {
        data: {
          ...desired,
          outputs: {
            assetId: asRobloxAssetId('9876543210'),
            iconAssetId: asRobloxAssetId('1122334455'),
          },
        },
        success: true,
      }
    },
  }
  return gamePassDriver
    .create({
      description: 'Grants VIP perks.',
      iconFileHash: asSha256Hex(
        'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      ),
      iconFilePath: 'assets/vip-icon.png',
      key: asResourceKey('vip-pass'),
      kind: 'gamePass',
      name: 'VIP Pass',
      price: undefined,
    })
    .then((result) => {
      expect(result.success).toBeTrue()
      if (result.success) {
        expect(result.data.outputs.assetId).toBe('9876543210')
      }
    })
})

it('Example 2', () => {
  const registry: DriverRegistry = {
    gamePass: {
      async create() {
        return { err: new OpenCloudError('not implemented'), success: false }
      },
    },
    place: {
      async create() {
        return { err: new OpenCloudError('not implemented'), success: false }
      },
    },
    universe: {
      async create() {
        return { err: new OpenCloudError('not implemented'), success: false }
      },
    },
  }
  expect(registry.gamePass).toBeObject()
})
