// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { BedrockState, StatePort } from '@bedrock-rbx/core'

it('Example 1', () => {
  const store = new Map<string, BedrockState>()
  const statePort: StatePort = {
    async read(environment) {
      return { data: store.get(environment), success: true }
    },
    async write(state) {
      store.set(state.environment, state)
      return { data: undefined, success: true }
    },
  }
  return statePort
    .read('production')
    .then((firstRead) => {
      expect(firstRead.success).toBeTrue()
      if (firstRead.success) {
        expect(firstRead.data).toBeUndefined()
      }
      return statePort.write({
        environment: 'production',
        resources: [],
        version: 1,
      })
    })
    .then((writeResult) => {
      expect(writeResult.success).toBeTrue()
      return statePort.read('production')
    })
    .then((secondRead) => {
      expect(secondRead.success).toBeTrue()
      if (secondRead.success && secondRead.data !== undefined) {
        expect(secondRead.data.environment).toBe('production')
        expect(secondRead.data.resources).toBeEmpty()
      }
    })
})
