// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import type { StateLockPort } from '@bedrock-rbx/core'

it('Example 1', () => {
  const held = new Set<string>()
  const lockPort: StateLockPort = {
    async acquire(environment) {
      if (held.has(environment)) {
        return {
          err: { reason: `${environment} is already held` },
          success: false,
        }
      }
      held.add(environment)
      return {
        data: {
          release: async () => {
            held.delete(environment)
            return { data: undefined, success: true }
          },
        },
        success: true,
      }
    },
  }
  return lockPort.acquire('production').then(async (first) => {
    expect(first.success).toBeTrue()
    const second = await lockPort.acquire('production')
    expect(second.success).toBeFalse()
    if (first.success) {
      await first.data.release()
    }
    const third = await lockPort.acquire('production')
    expect(third.success).toBeTrue()
  })
})
