// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import { createHttp1Dispatcher } from './http1-dispatcher'

it('Example 1', () => {
  expect(createHttp1Dispatcher({})).toBeUndefined()
})
