// DO NOT EDIT: Code generated by "generate-jsdoc-example-tests".
import { expect, it } from "vitest";
import {
  defaultRetryDelay,
  computeRetryWaitMs,
  shouldRetry,
  CREATE_METHOD_DEFAULTS,
  mergeConfig,
  type RetryResolvable,
  IDEMPOTENT_METHOD_DEFAULTS,
} from './retry'
import { RateLimitError } from '../../errors/rate-limit.ts'
import { ApiError } from '../../errors/api-error.ts'
import { NetworkError } from '../../errors/network-error.ts'

it('Example 1', () => {
  expect(defaultRetryDelay(0)).toBe(1000)
  expect(defaultRetryDelay(4)).toBe(16000)
  expect(defaultRetryDelay(10)).toBe(30000)
})

it('Example 2', () => {
  const error = new RateLimitError('slow down', { retryAfterSeconds: 3 })
  expect(
    computeRetryWaitMs(error, { attempt: 0, retryDelay: defaultRetryDelay }),
  ).toBe(3000)
})

it('Example 3', () => {
  const error = new ApiError('server error', { statusCode: 503 })
  expect(
    computeRetryWaitMs(error, { attempt: 2, retryDelay: defaultRetryDelay }),
  ).toBe(4000)
})

it('Example 4', () => {
  const error = new RateLimitError('', { retryAfterSeconds: 1 })
  expect(
    shouldRetry(error, {
      retryableStatuses: [429],
      retryableTransportCodes: [],
    }),
  ).toBe(true)
})

it('Example 5', () => {
  const reset = Object.assign(new Error('read ECONNRESET'), {
    code: 'ECONNRESET',
  })
  const error = new NetworkError('Network request failed', { cause: reset })
  expect(
    shouldRetry(error, {
      retryableStatuses: [],
      retryableTransportCodes: ['ECONNRESET'],
    }),
  ).toBe(true)
})

it('Example 6', () => {
  const clientConfig: RetryResolvable = {
    apiKey: 'k',
    baseUrl: 'https://apis.roblox.com',
    maxRetries: 3,
    retryableStatuses: [429, 500],
    retryableTransportCodes: [],
    retryDelay: defaultRetryDelay,
    timeout: 30000,
  }
  const merged = mergeConfig(clientConfig, {
    methodDefaults: CREATE_METHOD_DEFAULTS,
    methodKind: 'create',
  })
  expect(merged.retryableStatuses).toStrictEqual([429])
})

it('Example 7', () => {
  const clientConfig: RetryResolvable = {
    apiKey: 'k',
    baseUrl: 'https://apis.roblox.com',
    maxRetries: 3,
    retryableStatuses: [429],
    retryableTransportCodes: [],
    retryDelay: defaultRetryDelay,
    timeout: 30000,
  }
  const merged = mergeConfig(clientConfig, {
    methodDefaults: IDEMPOTENT_METHOD_DEFAULTS,
    methodKind: 'idempotent',
    requestOptions: { timeout: 10000 },
  })
  expect(merged.retryableStatuses).toStrictEqual([429])
  expect(merged.timeout).toBe(10000)
})
